/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as ShubhiMaheshwariApi from "../../../../../api";
import * as core from "../../../../../core";

export const CreateOfferBackendRequest: core.serialization.Schema<
    serializers.CreateOfferBackendRequest.Raw,
    ShubhiMaheshwariApi.CreateOfferBackendRequest
> = core.serialization.object({
    offerMeta: core.serialization.property(
        "offer_meta",
        core.serialization.lazyObject(async () => (await import("../../../..")).OfferMeta)
    ),
    offerTnc: core.serialization.property(
        "offer_tnc",
        core.serialization.lazyObject(async () => (await import("../../../..")).OfferTnc)
    ),
    offerDetails: core.serialization.property(
        "offer_details",
        core.serialization.lazyObject(async () => (await import("../../../..")).OfferDetails)
    ),
    offerValidations: core.serialization.property(
        "offer_validations",
        core.serialization.lazyObject(async () => (await import("../../../..")).OfferValidations)
    ),
});

export declare namespace CreateOfferBackendRequest {
    interface Raw {
        offer_meta: serializers.OfferMeta.Raw;
        offer_tnc: serializers.OfferTnc.Raw;
        offer_details: serializers.OfferDetails.Raw;
        offer_validations: serializers.OfferValidations.Raw;
    }
}
