/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors";
import * as ShubhiMaheshwariApi from "..";

export class BadRequestError extends errors.ShubhiMaheshwariApiError {
    constructor(body: ShubhiMaheshwariApi.LinkCancelledError) {
        super({
            message: "BadRequestError",
            statusCode: 400,
            body: body,
        });
        Object.setPrototypeOf(this, BadRequestError.prototype);
    }
}
