/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors";
import * as ShubhiMaheshwariApi from "..";

export class InternalServerError extends errors.ShubhiMaheshwariApiError {
    constructor(body: ShubhiMaheshwariApi.ApiError) {
        super({
            message: "InternalServerError",
            statusCode: 500,
            body: body,
        });
        Object.setPrototypeOf(this, InternalServerError.prototype);
    }
}
