/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "../../../..";

export interface CreateRefundRequest {
    /** Amount to be refunded. Should be lesser than or equal to the transaction amount. (Decimals allowed) */
    refundAmount: number;
    /** An unique ID to associate the refund with. Provie alphanumeric values <span style="white-space: nowrap">`<= 40 characters`</span> */
    refundId: string;
    /** A refund note for your reference. <span style="white-space: nowrap">`<= 100 characters`</span> */
    refundNote?: string;
    /** Speed at which the refund is processed. It's an optional field with default being STANDARD */
    refundSpeed?: ShubhiMaheshwariApi.CreateRefundRequestRefundSpeed;
    refundSplits?: ShubhiMaheshwariApi.VendorSplit[];
}
