/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as ShubhiMaheshwariApi from "../../../../api";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.tokenVault.fetchAllSavedInstruments.Response.Raw,
    ShubhiMaheshwariApi.FetchAllSavedInstruments[]
> = core.serialization.list(
    core.serialization.lazyObject(async () => (await import("../../..")).FetchAllSavedInstruments)
);

export declare namespace Response {
    type Raw = serializers.FetchAllSavedInstruments.Raw[];
}
