/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import * as ShubhiMaheshwariApi from "../../../api";
import * as core from "../../../core";

export const FetchPgReconRequest: core.serialization.Schema<
    serializers.FetchPgReconRequest.Raw,
    Omit<ShubhiMaheshwariApi.FetchPgReconRequest, "accept">
> = core.serialization.object({
    pagination: core.serialization.lazyObject(async () => (await import("../..")).FetchPgReconRequestPagination),
    filters: core.serialization.lazyObject(async () => (await import("../..")).FetchPgReconRequestFilters),
});

export declare namespace FetchPgReconRequest {
    interface Raw {
        pagination: serializers.FetchPgReconRequestPagination.Raw;
        filters: serializers.FetchPgReconRequestFilters.Raw;
    }
}
