/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * One of SUCCESS or PENDING
 */
export type AuthorizationInPaymentsEntityStatus = "SUCCESS" | "PENDING";

export const AuthorizationInPaymentsEntityStatus = {
    Success: "SUCCESS",
    Pending: "PENDING",
} as const;
