/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * One of CAPTURE or VOID
 */
export type AuthorizationInPaymentsEntityAction = "CAPTURE" | "VOID";

export const AuthorizationInPaymentsEntityAction = {
    Capture: "CAPTURE",
    Void: "VOID",
} as const;
