/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * One of [`flexmoney`, `zestmoney`, `hdfc`, `icici`, `cashe`, `idfc`, `kotak`]
 */
export type CardlessEmiProvider = "flexmoney" | "zestmoney" | "hdfc" | "icici" | "cashe" | "idfc" | "kotak";

export const CardlessEmiProvider = {
    Flexmoney: "flexmoney",
    Zestmoney: "zestmoney",
    Hdfc: "hdfc",
    Icici: "icici",
    Cashe: "cashe",
    Idfc: "idfc",
    Kotak: "kotak",
} as const;
