/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface CardlessEmiQueries {
    /** OrderId of the order. Either of `order_id` or `amount` is mandatory. <span style="white-space: nowrap">`<= 50 characters`</span> */
    orderId?: string;
    /** Amount of the order. OrderId of the order. Either of `order_id` or `amount` is mandatory. */
    amount?: number;
    customerDetails?: ShubhiMaheshwariApi.CustomerDetailsCardlessEmi;
}
