/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

/**
 * The card payment object is used to make payment using either plain card number, saved card instrument id or using cryptogram
 */
export interface CardPaymentMethod {
    card: ShubhiMaheshwariApi.Card;
}
