/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface CardOffer {
    type: ShubhiMaheshwariApi.CardArray[];
    /** Bank Name of Card. <span style="white-space: nowrap">`<= 100 characters`</span> */
    bankName: string;
    schemeName: ShubhiMaheshwariApi.SchemeArray[];
}
