/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface CardlessEmi {
    /** The channel for cardless EMI is always `link` */
    channel?: string;
    /** One of [`flexmoney`, `zestmoney`, `hdfc`, `icici`, `cashe`, `idfc`, `kotak`] */
    provider?: ShubhiMaheshwariApi.CardlessEmiProvider;
    /** Customers phone number for this payment instrument. If the customer is not eligible you will receive a 400 error with type as 'invalid_request_error' and code as 'invalid_request_error' */
    phone?: string;
    /** EMI tenure for the selected provider. This is mandatory when provider is one of [`hdfc`, `icici`, `cashe`, `idfc`, `kotak`] */
    emiTenure?: number;
}
