/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface CardlessEmiEntity {
    /** <span style="white-space: nowrap">`<= 50 characters`</span> */
    paymentMethod?: string;
    emiPlans?: ShubhiMaheshwariApi.EmiPlansArray[];
}
