/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The channel for card payments can be "link" or "post". Post is used for seamless OTP payments where merchant captures OTP on their own page.
 */
export type CardChannel = "link" | "post";

export const CardChannel = {
    Link: "link",
    Post: "post",
} as const;
