/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface Card {
    /** The channel for card payments can be "link" or "post". Post is used for seamless OTP payments where merchant captures OTP on their own page. */
    channel?: ShubhiMaheshwariApi.CardChannel;
    /** Customer card number for plain card transactions. Token pan number for tokenized card transactions. */
    cardNumber?: string;
    /** Customer name mentioned on the card. */
    cardHolderName?: string;
    /** Card expiry month for plain card transactions. Token expiry month for tokenized card transactions. */
    cardExpiryMm?: string;
    /** Card expiry year for plain card transactions. Token expiry year for tokenized card transactions. */
    cardExpiryYy?: string;
    /** CVV mentioned on the card. */
    cardCvv?: string;
    /** instrument id of saved card. Required only to make payment using saved instrument. */
    instrumentId?: string;
    /** cryptogram received from card network. Required only for tokenized card transactions. */
    cryptogram?: string;
    /** TRID issued by card networks. Required only for tokenized card transactions. */
    tokenRequestorId?: string;
    /** last 4 digits of original card number. Required only for tokenized card transactions. */
    cardDisplay?: string;
    /** Card alias as returned by Cashfree Vault API. */
    cardAlias?: string;
    /** One of ["Kotak", "ICICI", "RBL", "BOB", "Standard Chartered"]. Card bank name, required for EMI payments. This is the bank user has selected for EMI */
    cardBankName?: ShubhiMaheshwariApi.CardCardBankName;
    /** EMI tenure selected by the user */
    emiTenure?: number;
}
