/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * One of ["Kotak", "ICICI", "RBL", "BOB", "Standard Chartered"]. Card bank name, required for EMI payments. This is the bank user has selected for EMI
 */
export type CardCardBankName = "Kotak" | "ICICI" | "RBL" | "BOB" | "Standard Chartered";

export const CardCardBankName = {
    Kotak: "Kotak",
    Icici: "ICICI",
    Rbl: "RBL",
    Bob: "BOB",
    StandardChartered: "Standard Chartered",
} as const;
