/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface CardEmi {
    /** The channel for card payments will always be "link" */
    channel?: string;
    /** Customer card number. */
    cardNumber?: string;
    /** Customer name mentioned on the card. */
    cardHolderName?: string;
    /** Card expiry month. */
    cardExpiryMm?: string;
    /** Card expiry year. */
    cardExpiryYy?: string;
    /** CVV mentioned on the card. */
    cardCvv?: string;
    /** Card alias as returned by Cashfree Vault API */
    cardAlias?: string;
    /** Card bank name, required for EMI payments. This is the bank user has selected for EMI. One of ["hdfc, "kotak", "icici", "rbl", "bob", "standard chartered", "axis", "au", "yes", "sbi", "fed", "hsbc", "citi", "amex"] */
    cardBankName?: ShubhiMaheshwariApi.CardEmiCardBankName;
    /** EMI tenure selected by the user */
    emiTenure?: number;
}
