/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of discount
 */
export type CashbackDetailsCashbackType = "flat" | "percentage";

export const CashbackDetailsCashbackType = {
    Flat: "flat",
    Percentage: "percentage",
} as const;
