/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Speed at which the refund is processed. It's an optional field with default being STANDARD
 */
export type CreateRefundRequestRefundSpeed = "STANDARD" | "INSTANT";

export const CreateRefundRequestRefundSpeed = {
    Standard: "STANDARD",
    Instant: "INSTANT",
} as const;
