/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Cryptogram {
    /** instrument_id of saved instrument */
    instrumentId?: string;
    /** TRID issued by card networks */
    tokenRequestorId?: string;
    /** token pan number */
    cardNumber?: string;
    /** token pan expiry month */
    cardExpiryMm?: string;
    /** token pan expiry year */
    cardExpiryYy?: string;
    /** cryptogram */
    cryptogram?: string;
    /** last 4 digits of original card number */
    cardDisplay?: string;
}
