/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Details of the customer for whom eligibility is being checked.
 */
export interface CustomerDetailsCardlessEmi {
    /** Phone Number of the customer <span style="white-space: nowrap">`<= 50 characters`</span> */
    customerPhone: string;
}
