/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The customer details that are necessary. Note that you can pass dummy details if your use case does not require the customer details.
 */
export interface CustomerDetails {
    /** A unique identifier for the customer. Use alphanumeric values only. <span style="white-space: nowrap">`<= 50 characters`</span> */
    customerId: string;
    /** Customer email address. <span style="white-space: nowrap">`<= 100 characters`</span> */
    customerEmail?: string;
    /** Customer phone number. <span style="white-space: nowrap">`<= 10 characters`</span> */
    customerPhone: string;
    /** Customer bank account. Required if you want to do a bank account check (TPV) <span style="white-space: nowrap">`<= 20 characters`</span> */
    customerBankAccountNumber?: string;
    /** Customer bank IFSC. Required if you want to do a bank account check (TPV) */
    customerBankIfsc?: string;
    /** Customer bank code. Required for net banking payments, if you want to do a bank account check (TPV) */
    customerBankCode?: string;
}
