/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface DiscountDetails {
    /** Type of discount */
    discountType: ShubhiMaheshwariApi.DiscountDetailsDiscountType;
    /** Value of Discount. <span style="white-space: nowrap">`<= 100 characters`</span> */
    discountValue: string;
    /** Maximum Value of Discount allowed. <span style="white-space: nowrap">`<= 100 characters`</span> */
    maxDiscountAmount: string;
}
