/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface EligibleCardlessEmiEntity {
    eligibility?: string;
    entityType?: string;
    entityValue?: string;
    entityDetails?: ShubhiMaheshwariApi.CardlessEmiEntity;
}
