/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface EmiOffer {
    /** Type of emi offer. Possible values are `credit_card_emi`, `debit_card_emi`, `cardless_emi` <span style="white-space: nowrap">`<= 100 characters`</span> */
    type: string;
    /** Bank Name <span style="white-space: nowrap">`<= 100 characters`</span> */
    bankName: string;
    tenures?: ShubhiMaheshwariApi.TenuresArray[];
}
