/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EmiPlansArray {
    tenure?: number;
    interestRate?: number;
    /** <span style="white-space: nowrap">`<= 50 characters`</span> */
    currency?: string;
    emi?: number;
    totalInterest?: number;
    totalAmount?: number;
}
