/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface ErrorResponse {
    message?: string;
    code?: string;
    /** One of ["invalid_request_error", "authentication_error", "rate_limit_error", "validation_error", "api_error"] */
    type?: ShubhiMaheshwariApi.ErrorResponseType;
}
