/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * One of ["invalid_request_error", "authentication_error", "rate_limit_error", "validation_error", "api_error"]
 */
export type ErrorResponseType =
    | "invalid_request_error"
    | "authentication_error"
    | "rate_limit_error"
    | "validation_error"
    | "api_error";

export const ErrorResponseType = {
    InvalidRequestError: "invalid_request_error",
    AuthenticationError: "authentication_error",
    RateLimitError: "rate_limit_error",
    ValidationError: "validation_error",
    ApiError: "api_error",
} as const;
