/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The error details are present only for failed payments
 */
export interface ErrorDetailsInPaymentsEntity {
    errorCode?: string;
    errorDescription?: string;
    errorReason?: string;
    errorSource?: string;
}
