/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface FetchSettlement {
    /** Specify a value from where you want to fetch the settlement details in the API call. */
    cursor?: string;
    /** Specify the number of settlements you want to fetch in the API call. */
    limit?: number;
    data?: ShubhiMaheshwariApi.FetchSettlementDataItem[];
}
