/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Status of the saved instrument.
 */
export type FetchAllSavedInstrumentsInstrumentStatus = "ACTIVE" | "INACTIVE";

export const FetchAllSavedInstrumentsInstrumentStatus = {
    Active: "ACTIVE",
    Inactive: "INACTIVE",
} as const;
