/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FetchSettlementDataItem {
    /** Event type is SETTLEMENT. */
    eventType?: string;
    /** Unique ID to identify the settlement. */
    cfSettlementId?: number;
    /** Status of the settlement. */
    status?: string;
    /** Date and time when the settlement was processed. */
    settlementDate?: string;
    /** Amount captured. */
    paymentAmount?: number;
    /** Unique transaction reference number of the payment. */
    settlementUtr?: string;
    /** Amount that is adjusted from the settlement amount. */
    adjustment?: number;
    /** Service tax applicable on settlement. */
    serviceTax?: number;
    /** Service charge applicable on settlement. */
    serviceCharge?: number;
    /** Net amount that is settled after deducting the settlement charges and tax. (Settlement charges and tax is applicable for instant and on demand settlements.) */
    amountSettled?: number;
    /** The start time of time range of settlement. */
    paymentFrom?: string;
    /** The end time of time range of settlement */
    paymentTill?: string;
    /** Reason for failure. */
    reason?: string;
    /** Settlement initiation time. */
    settlementInitiatedOn?: string;
    /** Settlement type. */
    settlementType?: string;
    /** Settlement tax applicable on settlement. */
    settlementCharge?: number;
    /** Settlement charge applicable on settlement. */
    settlementTax?: number;
    /** Remarks on the settlement. */
    remarks?: string;
}
