/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FetchPgReconRequestFilters {
    /** Specify the start date from when you want the settlement reconciliation details. */
    startDate: string;
    /** Specify the end date till when you want the settlement reconciliation details. */
    endDate: string;
}
