/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface FetchPgRecon {
    /** Specifies from where the next set of settlement details should be fetched. */
    cursor?: string;
    /** Number of settlements you want to fetch in the next iteration. */
    limit?: number;
    data?: ShubhiMaheshwariApi.FetchPgReconDataItem[];
}
