/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FetchSettlementReconDataItem {
    /** Unique ID associated with the event. */
    eventId?: string;
    /** The event type can be PAYMENT, REFUND, REFUND_REVERSAL, DISPUTE, DISPUTE_REVERSAL, CHARGEBACK, CHARGEBACK_REVERSAL, OTHER_ADJUSTMENT. */
    eventType?: string;
    /** Amount that is part of the settlement corresponding to the event. */
    eventSettlementAmount?: number;
    /** Amount corresponding to the event. Example, refund amount, dispute amount, payment amount, etc. */
    eventAmount?: number;
    /** Indicates if it is CREDIT/DEBIT sale. */
    saleType?: string;
    /** Status of the event. Example - SUCCESS, FAILED, PENDING, CANCELLED. */
    eventStatus?: string;
    /** Recon */
    entity?: string;
    /** Time associated with the event. Example, transaction time, dispute initiation time */
    eventTime?: string;
    /** Curreny type - INR. */
    eventCurrency?: string;
    /** Unique order ID. Alphanumeric and only '-' and '_' allowed. */
    orderId?: string;
    /** The amount which was passed at the order creation time. */
    orderAmount?: number;
    /** Customer phone number. */
    customerPhone?: string;
    /** Customer email. */
    customerEmail?: string;
    /** Customer name. */
    customerName?: string;
    /** Payment amount captured. */
    paymentAmount?: number;
    /** Unique transaction reference number of the payment. */
    paymentUtr?: string;
    /** Date and time when the payment was initiated. */
    paymentTime?: string;
    /** Service charge applicable for the payment. */
    paymentServiceCharge?: number;
    /** Service tax applicable on the payment. */
    paymentServiceTax?: number;
    /** Cashfree Payments unique ID to identify a payment. */
    cfPaymentId?: number;
    /** Unique ID to identify the settlement. */
    cfSettlementId?: number;
    /** Date and time when the settlement was processed. */
    settlementDate?: string;
    /** Unique transaction reference number of the settlement. */
    settlementUtr?: string;
    /** Service charge that is applicable for splitting the payment. */
    splitServiceCharge?: number;
    /** Service tax applicable for splitting the amount to vendors. */
    splitServiceTax?: number;
    /** Vendor commission applicable for this transaction. */
    vendorCommission?: number;
    /** Specifies whether the dispute was closed in favor of the merchant or customer. Possible values - Merchant, Customer. */
    closedInFavorOf?: string;
    /** Date and time when the dispute was resolved. */
    disputeResolvedOn?: string;
    /** Category of the dispute - Dispute code and the reason for dispute is shown. */
    disputeCategory?: string;
    /** Note regarding the dispute. */
    disputeNote?: string;
    /** Date and time when the refund was processed. */
    refundProcessedAt?: string;
    /** The bank reference number for refund. */
    refundArn?: string;
    /** A refund note for your reference. */
    refundNote?: string;
    /** An unique ID associated with the refund. */
    refundId?: string;
    /** Other adjustment remarks. */
    adjustmentRemarks?: string;
}
