/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Specify either the Settlement ID, Settlement UTR, or start date and end date to fetch the settlement details.
 */
export interface FetchSettlementReconRequestFilters {
    /** List of settlement IDs for which you want the settlement reconciliation details. */
    cfSettlementIds?: number[];
    /** List of settlement UTRs for which you want the settlement reconciliation details. */
    settlementUtrs?: string[];
    /** Specify the start date from when you want the settlement reconciliation details. */
    startDate?: string;
    /** Specify the end date till when you want the settlement reconciliation details. */
    endDate?: string;
}
