/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export type GetPaymentsfororderResponse = ShubhiMaheshwariApi.PaymentsEntity | ShubhiMaheshwariApi.PaymentsEntity;
