/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface LinkCustomerDetailsEntity {
    /** Customer phone number */
    customerPhone: string;
    /** Customer email address */
    customerEmail?: string;
    /** Customer name */
    customerName?: string;
}
