/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface LinkCancelledResponse {
    cfLinkId?: number;
    linkId?: string;
    linkStatus?: string;
    linkCurrency?: string;
    linkAmount?: number;
    linkAmountPaid?: number;
    linkPartialPayments?: boolean;
    linkMinimumPartialAmount?: number;
    linkPurpose?: string;
    linkCreatedAt?: string;
    customerDetails?: ShubhiMaheshwariApi.LinkCustomerDetailsEntity;
    linkMeta?: ShubhiMaheshwariApi.LinkMetaEntity;
    linkUrl?: string;
    linkExpiryTime?: string;
    linkNotes?: ShubhiMaheshwariApi.LinkNotesEntity;
    linkAutoReminders?: boolean;
    linkNotify?: ShubhiMaheshwariApi.LinkNotifyEntity;
}
