/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface LinkMetaEntity {
    /** Notification URL for server-server communication. It should be an https URL. */
    notifyUrl?: string;
    /** If "true", link will directly open UPI Intent flow on mobile, and normal link flow elsewhere */
    upiIntent?: boolean;
    /** The URL to which user will be redirected to after the payment is done on the link. Maximum length: 250. */
    returnUrl?: string;
    /** Allowed payment modes for this link. Pass comma-separated values among following options - "cc", "dc", "ccc", "ppc", "nb", "upi", "paypal", "app". Leave it blank to show all available payment methods */
    paymentMethods?: string;
}
