/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface LinkOrdersResponse {
    cfOrderId?: number;
    orderId?: string;
    entity?: string;
    orderCurrency?: string;
    orderAmount?: number;
    orderStatus?: string;
    orderToken?: string;
    orderExpiryTime?: string;
    orderNote?: string;
    customerDetails?: ShubhiMaheshwariApi.LinkCustomerDetailsEntity;
    payments?: ShubhiMaheshwariApi.PaymentUrlObject;
    settlements?: ShubhiMaheshwariApi.SettlementUrlObject;
    refunds?: ShubhiMaheshwariApi.RefundUrlObject;
}
