/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface LinkNotifyEntity {
    /** If "true", Cashfree will send sms on customer_phone */
    sendSms?: boolean;
    /** If "true", Cashfree will send email on customer_email */
    sendEmail?: boolean;
}
