/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Key-value pair that can be used to store additional information about the entity. Maximum 5 key-value pairs
 */
export type LinkNotesEntity = Record<string, string>;
