/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Netbanking {
    /** The channel for netbanking will always be `link` */
    channel: string;
    /** Bank code */
    netbankingBankCode: number;
}
