/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Offer Type for the Offer.
 */
export type OfferDetailsOfferType = "DISCOUNT" | "CASHBACK" | "DISCOUNT_AND_CASHBACK" | "NO_COST_EMI";

export const OfferDetailsOfferType = {
    Discount: "DISCOUNT",
    Cashback: "CASHBACK",
    DiscountAndCashback: "DISCOUNT_AND_CASHBACK",
    NoCostEmi: "NO_COST_EMI",
} as const;
