/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface OfferDetails {
    /** Offer Type for the Offer. */
    offerType: ShubhiMaheshwariApi.OfferDetailsOfferType;
    discountDetails?: ShubhiMaheshwariApi.DiscountDetails;
    cashbackDetails?: ShubhiMaheshwariApi.CashbackDetails;
}
