/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * TnC Type for the Offer. It can be either `text` or `link`
 */
export type OfferTncOfferTncType = "link" | "post";

export const OfferTncOfferTncType = {
    Link: "link",
    Post: "post",
} as const;
