/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface OfferQueries {
    /** OrderId of the order. Either of `order_id` or `order_amount` is mandatory. <span style="white-space: nowrap">`<= 50 characters`</span> */
    orderId?: string;
    /** Amount of the order. OrderId of the order. Either of `order_id` or `order_amount` is mandatory. */
    amount?: number;
}
