/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface OfferEntity {
    offerId?: number;
    offerStatus?: string;
    offerMeta?: ShubhiMaheshwariApi.OfferMeta;
    offerTnc?: ShubhiMaheshwariApi.OfferTnc;
    offerDetails?: ShubhiMaheshwariApi.OfferDetails;
    offerValidations?: ShubhiMaheshwariApi.OfferValidations;
}
