/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type OfferType = "DISCOUNT" | "CASHBACK" | "DISCOUNT_AND_CASHBACK" | "NO_COST_EMI";

export const OfferType = {
    Discount: "DISCOUNT",
    Cashback: "CASHBACK",
    DiscountAndCashback: "DISCOUNT_AND_CASHBACK",
    NoCostEmi: "NO_COST_EMI",
} as const;
