/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface OfferMeta {
    /** Title for the Offer. <span style="white-space: nowrap">`<= 50 characters`</span> */
    offerTitle: string;
    /** Description for the Offer. <span style="white-space: nowrap">`<= 100 characters`</span> */
    offerDescription: string;
    /** Unique identifier for the Offer. <span style="white-space: nowrap">`<= 10 characters`</span> */
    offerCode: string;
    /** Start Time for the Offer <span style="white-space: nowrap">`<= 20 characters`</span> */
    offerStartTime: string;
    /** Expiry Time for the Offer */
    offerEndTime: string;
}
