/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export type OfferValidationsPaymentMethod =
    | ShubhiMaheshwariApi.OfferAll
    | ShubhiMaheshwariApi.OfferCard
    | ShubhiMaheshwariApi.OfferNb
    | ShubhiMaheshwariApi.OfferWallet
    | ShubhiMaheshwariApi.OfferUpi
    | ShubhiMaheshwariApi.OfferPaylater
    | ShubhiMaheshwariApi.OfferEmi;
