/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface OfferValidations {
    /** Minimum Amount for Offer to be Applicable <span style="white-space: nowrap">`<= 50 characters`</span> */
    minAmount?: string;
    paymentMethod: ShubhiMaheshwariApi.OfferValidationsPaymentMethod;
    /** Maximum amount of Offer that can be availed. <span style="white-space: nowrap">`<= 100 characters`</span> */
    maxAllowed: string;
}
