/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface OfferFilters {
    /** Array of offer_type to be filtered. */
    offerType?: ShubhiMaheshwariApi.OfferType[];
}
