/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export type OrderPayRequestPaymentMethod =
    | ShubhiMaheshwariApi.CardPaymentMethod
    | ShubhiMaheshwariApi.UpiPaymentMethod
    | ShubhiMaheshwariApi.NetBankingPaymentMethod
    | ShubhiMaheshwariApi.AppPaymentMethod
    | ShubhiMaheshwariApi.CardEmiPaymentMethod
    | ShubhiMaheshwariApi.CardlessEmiPaymentMethod
    | ShubhiMaheshwariApi.PaylaterPaymentMethod;
