/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * One of ["link", "collect", "qrcode"]. In an older version we used to support different channels like 'gpay', 'phonepe' etc. However, we now support only the following channels - link, collect and qrcode. To process payments using gpay, you will have to provide channel as 'link' and provider as 'gpay'
 */
export type OrderPayResponseChannel = "link" | "collect" | "qrcode";

export const OrderPayResponseChannel = {
    Link: "link",
    Collect: "collect",
    Qrcode: "qrcode",
} as const;
