/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * One of ["link", "custom", "form"]
 */
export type OrderPayResponseAction = "link" | "custom" | "form";

export const OrderPayResponseAction = {
    Link: "link",
    Custom: "custom",
    Form: "form",
} as const;
