/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface OrderPayData {
    url?: string;
    payload?: Record<string, unknown>;
    contentType?: string;
    method?: string;
}
