/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface OrderPayResponse {
    /** Payment identifier created by Cashfree */
    cfPaymentId?: number;
    /** One of ["upi", "netbanking", "card", "app", "cardless_emi", "paylater"] */
    paymentMethod?: ShubhiMaheshwariApi.OrderPayResponsePaymentMethod;
    /** One of ["link", "collect", "qrcode"]. In an older version we used to support different channels like 'gpay', 'phonepe' etc. However, we now support only the following channels - link, collect and qrcode. To process payments using gpay, you will have to provide channel as 'link' and provider as 'gpay' */
    channel?: ShubhiMaheshwariApi.OrderPayResponseChannel;
    /** One of ["link", "custom", "form"] */
    action?: ShubhiMaheshwariApi.OrderPayResponseAction;
    data?: ShubhiMaheshwariApi.OrderPayData;
}
