/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface OrdersEntity {
    cfOrderId?: number;
    orderId?: string;
    entity?: string;
    orderCurrency?: string;
    orderAmount?: number;
    orderStatus?: string;
    paymentSessionId?: string;
    orderExpiryTime?: string;
    orderNote?: string;
    customerDetails?: ShubhiMaheshwariApi.CustomerDetails;
    orderMeta?: ShubhiMaheshwariApi.OrderMeta;
    payments?: ShubhiMaheshwariApi.PaymentUrlObject;
    settlements?: ShubhiMaheshwariApi.SettlementUrlObject;
    refunds?: ShubhiMaheshwariApi.RefundUrlObject;
}
