/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

/**
 * This is the response shared when merchant inovkes the OTP submit or resend API
 */
export interface OtpResponseEntity {
    /** The payment id for which this request was sent */
    cfPaymentId?: number;
    /** The action that was invoked for this request. */
    action?: ShubhiMaheshwariApi.OtpResponseEntityAction;
    /** Status of the is action. Will be either failed or successful. If the action is successful, you should still call the authorization status to verify the final payment status. */
    authenticateStatus?: ShubhiMaheshwariApi.OtpResponseEntityAuthenticateStatus;
    /** Human readable message which describes the status in more detail */
    paymentMessage?: string;
}
