/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The action for this workflow. Could be either SUBMIT_OTP or RESEND_OTP
 */
export type OtpRequestAction = "SUBMIT_OTP" | "RESEND_OTP";

export const OtpRequestAction = {
    SubmitOtp: "SUBMIT_OTP",
    ResendOtp: "RESEND_OTP",
} as const;
