/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Status of the is action. Will be either failed or successful. If the action is successful, you should still call the authorization status to verify the final payment status.
 */
export type OtpResponseEntityAuthenticateStatus = "FAILED" | "SUCCESS";

export const OtpResponseEntityAuthenticateStatus = {
    Failed: "FAILED",
    Success: "SUCCESS",
} as const;
