/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The action that was invoked for this request.
 */
export type OtpResponseEntityAction = "SUBMIT_OTP" | "RESEND_OTP";

export const OtpResponseEntityAction = {
    SubmitOtp: "SUBMIT_OTP",
    ResendOtp: "RESEND_OTP",
} as const;
