/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * One of ["kotak", "flexipay", "zestmoney", "lazypay", "olapostpaid","simpl", "freechargepaylater"]. Please note that Flexipay is offered by HDFC bank
 */
export type PaylaterProvider =
    | "kotak"
    | "flexipay"
    | "zestmoney"
    | "lazypay"
    | "olapostpaid"
    | "simpl"
    | "freechargepaylater";

export const PaylaterProvider = {
    Kotak: "kotak",
    Flexipay: "flexipay",
    Zestmoney: "zestmoney",
    Lazypay: "lazypay",
    Olapostpaid: "olapostpaid",
    Simpl: "simpl",
    Freechargepaylater: "freechargepaylater",
} as const;
