/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PaymentMethodNetBankingInPaymentsEntity {
    channel: string;
    netbankingBankCode: string;
    netbankingBankName: string;
}
