/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PaymentMethodCardlessEmiInPaymentsEntity {
    channel?: string;
    provider?: string;
    phone?: string;
}
