/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PaymentMethodCardInPaymentsEntity {
    channel?: string;
    cardNumber?: string;
    cardNetwork?: string;
    cardType?: string;
    cardCountry?: string;
    cardBankName?: string;
    cardNetworkReferenceId?: string;
}
