/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface PaymentSuccessWebhook {
    data?: ShubhiMaheshwariApi.WHdata;
    eventTime?: string;
    type?: string;
}
