/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface PaymentsEntity {
    cfPaymentId?: number;
    orderId?: string;
    entity?: string;
    errorDetails?: ShubhiMaheshwariApi.ErrorDetailsInPaymentsEntity;
    isCaptured?: boolean;
    /** Order amount can be different from payment amount if you collect service fee from the customer */
    orderAmount?: number;
    /** Type of payment group. One of ['upi', 'card', 'app', 'netbanking', 'paylater', 'cardless_emi'] */
    paymentGroup?: string;
    paymentCurrency?: string;
    paymentAmount?: number;
    /** This is the time when the payment was initiated */
    paymentTime?: string;
    /** This is the time when the payment reaches its terminal state */
    paymentCompletionTime?: string;
    /** The transaction status can be one of  ["SUCCESS", "NOT_ATTEMPTED", "FAILED", "USER_DROPPED", "VOID", "CANCELLED", "PENDING"] */
    paymentStatus?: ShubhiMaheshwariApi.PaymentsEntityPaymentStatus;
    paymentMessage?: string;
    bankReference?: string;
    authId?: string;
    authorization?: ShubhiMaheshwariApi.AuthorizationInPaymentsEntity;
    paymentMethod?: ShubhiMaheshwariApi.PaymentMethodInPaymentsEntity;
}
