/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export type PaymentMethodInPaymentsEntityPaymentMethod =
    | ShubhiMaheshwariApi.PaymentMethodCardInPaymentsEntity
    | ShubhiMaheshwariApi.PaymentMethodNetBankingInPaymentsEntity
    | ShubhiMaheshwariApi.PaymentMethodUpiInPaymentsEntity
    | ShubhiMaheshwariApi.PaymentMethodAppInPaymentsEntity
    | ShubhiMaheshwariApi.PaymentMethodCardlessEmiInPaymentsEntity
    | ShubhiMaheshwariApi.PaymentMethodPaylaterInPaymentsEntity;
