/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RefundSpeed {
    /** Requested speed of refund. */
    requested?: string;
    /** Accepted speed of refund. */
    accepted?: string;
    /** Processed speed of refund. */
    processed?: string;
    /** Error message, if any for refund_speed request */
    message?: string;
}
