/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface RefundsEntity {
    /** Cashfree Payments ID of the payment for which refund is initiated */
    cfPaymentId?: number;
    /** Cashfree Payments ID for a refund */
    cfRefundId?: string;
    /** Merchant’s order Id of the order for which refund is initiated */
    orderId?: string;
    /** Merchant’s refund ID of the refund */
    refundId?: string;
    entity?: "refund";
    /** Amount that is refunded */
    refundAmount?: number;
    /** Currency of the refund amount */
    refundCurrency?: string;
    /** Note added by merchant for the refund */
    refundNote?: string;
    /** This can be one of ["SUCCESS", "PENDING", "CANCELLED", "ONHOLD", "FAILED"] */
    refundStatus?: ShubhiMaheshwariApi.RefundsEntityRefundStatus;
    /** The bank reference number for refund */
    refundArn?: string;
    /** Charges in INR for processing refund */
    refundCharge?: number;
    /** Description of refund status */
    statusDescription?: string;
    /** Key-value pair that can be used to store additional information about the entity. Maximum 5 key-value pairs */
    metadata?: Record<string, unknown>;
    refundSplits?: ShubhiMaheshwariApi.VendorSplit[];
    /** This can be one of ["PAYMENT_AUTO_REFUND", "MERCHANT_INITIATED", "UNRECONCILED_AUTO_REFUND"] */
    refundType?: ShubhiMaheshwariApi.RefundsEntityRefundType;
    /** Method or speed of processing refund */
    refundMode?: ShubhiMaheshwariApi.RefundsEntityRefundMode;
    /** Time of refund creation */
    createdAt?: string;
    /** Time when refund was processed successfully */
    processedAt?: string;
    refundSpeed?: ShubhiMaheshwariApi.RefundSpeed;
}
