/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Method or speed of processing refund
 */
export type RefundsEntityRefundMode = "STANDARD" | "INSTANT";

export const RefundsEntityRefundMode = {
    Standard: "STANDARD",
    Instant: "INSTANT",
} as const;
