/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This can be one of ["PAYMENT_AUTO_REFUND", "MERCHANT_INITIATED", "UNRECONCILED_AUTO_REFUND"]
 */
export type RefundsEntityRefundType = "PAYMENT_AUTO_REFUND" | "MERCHANT_INITIATED" | "UNRECONCILED_AUTO_REFUND";

export const RefundsEntityRefundType = {
    PaymentAutoRefund: "PAYMENT_AUTO_REFUND",
    MerchantInitiated: "MERCHANT_INITIATED",
    UnreconciledAutoRefund: "UNRECONCILED_AUTO_REFUND",
} as const;
