/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SettlementsEntity {
    cfPaymentId?: string;
    cfSettlementId?: string;
    settlementCurrency?: string;
    orderId?: string;
    entity?: string;
    orderAmount?: number;
    paymentTime?: string;
    serviceCharge?: number;
    serviceTax?: number;
    settlementAmount?: number;
    settlementId?: number;
    transferId?: number;
    transferTime?: string;
    transferUtr?: string;
}
