/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TerminalResponse {
    addedOn?: string;
    cfTerminalId?: string;
    lastUpdatedOn?: string;
    terminalArea?: string;
    teminalId?: string;
    terminalName?: string;
    terminalNote?: string;
    terminalPhoneNo?: string;
    terminalStatus?: string;
}
