/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TerminalDetails {
    /** Phone no assigned to the terminal <span style="white-space: nowrap">`<= 10 characters`</span> */
    terminalPhoneNo: string;
    /** The internal id that you use to map the terminal in your internal system <span style="white-space: nowrap">`<= 100 characters`</span> */
    terminalId: string;
    /** To identify the type of terminal product in use, in this case it is SPOS <span style="white-space: nowrap">`<= 10 characters`</span> */
    terminalType: string;
}
