/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "..";

export interface Upi {
    /** Specify the channel through which the payment must be processed. Can be one of ["link", "collect", "qrcode"] */
    channel: ShubhiMaheshwariApi.UpiChannel;
    /** Customer UPI VPA to process payment. */
    upiId?: string;
    /** The UPI request will be valid for this expiry minutes. This parameter is only applicable for a UPI collect payment. The default value is 5 minutes. You should keep the minimum as 5 minutes, and maximum as 15 minutes */
    upiExpiryMinutes?: number;
    /** For one time mandate on UPI. Set this as authorize_only = true. Please note that you can only use the "collect" channel if you are sending a one time mandate request */
    authorizeOnly?: boolean;
    authorization?: ShubhiMaheshwariApi.UpiAuthorizeDetails;
}
