/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpiAuthorizeDetails {
    /** Time by which this authorization should be approved by the customer. */
    approveBy?: string;
    /** This is the time when the UPI one time mandate will start */
    startTime?: string;
    /** This is the time when the UPI mandate will be over. If the mandate has not been executed by this time, the funds will be returned back to the customer after this time. */
    endTime?: string;
}
