/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Specify the channel through which the payment must be processed. Can be one of ["link", "collect", "qrcode"]
 */
export type UpiChannel = "link" | "collect" | "qrcode";

export const UpiChannel = {
    Link: "link",
    Collect: "collect",
    Qrcode: "qrcode",
} as const;
