/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WHcard {
    channel?: string;
    cardNumber?: string;
    cardNetwork?: string;
    cardType?: string;
    cardCounty?: string;
    cardBankName?: string;
}
