/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WHcustomerDetails {
    customerName?: string;
    customerId?: string;
    customerEmail?: string;
    customerPhone?: string;
}
