/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WHorder {
    orderId?: string;
    orderAmount?: number;
    orderCurrency?: string;
    orderTags?: string;
}
