/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as ShubhiMaheshwariApi from "../../../../../api";
import * as core from "../../../../../core";

export const CreateOrderBackendRequest: core.serialization.Schema<
    serializers.CreateOrderBackendRequest.Raw,
    ShubhiMaheshwariApi.CreateOrderBackendRequest
> = core.serialization.object({
    orderId: core.serialization.property("order_id", core.serialization.string().optional()),
    orderAmount: core.serialization.property("order_amount", core.serialization.number()),
    orderCurrency: core.serialization.property("order_currency", core.serialization.string()),
    customerDetails: core.serialization.property(
        "customer_details",
        core.serialization.lazyObject(async () => (await import("../../../..")).CustomerDetails)
    ),
    terminal: core.serialization.lazyObject(async () => (await import("../../../..")).TerminalDetails).optional(),
    orderMeta: core.serialization.property(
        "order_meta",
        core.serialization.lazyObject(async () => (await import("../../../..")).OrderMeta).optional()
    ),
    orderExpiryTime: core.serialization.property("order_expiry_time", core.serialization.string().optional()),
    orderNote: core.serialization.property("order_note", core.serialization.string().optional()),
    orderTags: core.serialization.property(
        "order_tags",
        core.serialization.record(core.serialization.string(), core.serialization.string()).optional()
    ),
    orderSplits: core.serialization.property(
        "order_splits",
        core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../../..")).VendorSplit))
            .optional()
    ),
});

export declare namespace CreateOrderBackendRequest {
    interface Raw {
        order_id?: string | null;
        order_amount: number;
        order_currency: string;
        customer_details: serializers.CustomerDetails.Raw;
        terminal?: serializers.TerminalDetails.Raw | null;
        order_meta?: serializers.OrderMeta.Raw | null;
        order_expiry_time?: string | null;
        order_note?: string | null;
        order_tags?: Record<string, string> | null;
        order_splits?: serializers.VendorSplit.Raw[] | null;
    }
}
