/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "../..";

export interface PostSettlementsRequest {
    /**
     * application/json
     */
    accept?: string;
    body: ShubhiMaheshwariApi.FetchSettlementReconRequest;
}
