/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "../../../..";

export interface AuthorizationRequest {
    /** Type of authorization to run. Can be one of 'CAPTURE' , 'VOID' */
    action?: ShubhiMaheshwariApi.AuthorizationRequestAction;
    /** The amount if you are running a 'CAPTURE' */
    amount?: number;
}
