/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "../../../..";

export interface CreateOrderBackendRequest {
    clientId: string;
    clientSecret: string;
    /** Order identifier present in your system. Alphanumeric and only - and _ allowed. <span style="white-space: nowrap">`<= 45 characters`</span> */
    orderId?: string;
    /** Bill amount for the order. Provide upto two decimals. 10.15 means Rs 10 and 15 paisa */
    orderAmount: number;
    /** Currency for the order. INR if left empty. Contact care@cashfree.com to enable new currencies. */
    orderCurrency: string;
    customerDetails: ShubhiMaheshwariApi.CustomerDetails;
    terminal?: ShubhiMaheshwariApi.TerminalDetails;
    orderMeta?: ShubhiMaheshwariApi.OrderMeta;
    /** Time after which the order expires. Customers will not be able to make the payment beyond the time specified here. We store timestamps in IST, but you can provide them in a valid ISO 8601 time format. */
    orderExpiryTime?: string;
    /** Order note for reference. <span style="white-space: nowrap">`<= 200 characters`</span> */
    orderNote?: string;
    /** Custom Tags which can be passed for an order. A maximum of 6 tags can be added */
    orderTags?: Record<string, string>;
    orderSplits?: ShubhiMaheshwariApi.VendorSplit[];
}
