/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "../../../..";

export interface OrderPayRequest {
    paymentSessionId: string;
    paymentMethod: ShubhiMaheshwariApi.OrderPayRequestPaymentMethod;
    saveInstrument?: boolean;
    /** This is required if any offers needs to be applied to the order. */
    offerId?: string;
}
