/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as ShubhiMaheshwariApi from "../../../../../api";
import * as core from "../../../../../core";

export const CreateTerminalRequest: core.serialization.Schema<
    serializers.CreateTerminalRequest.Raw,
    ShubhiMaheshwariApi.CreateTerminalRequest
> = core.serialization.object({
    terminalId: core.serialization.property("terminal_id", core.serialization.string().optional()),
    terminalName: core.serialization.property("terminal_name", core.serialization.string()),
    terminalPhoneNo: core.serialization.property("terminal_phone_no", core.serialization.string()),
});

export declare namespace CreateTerminalRequest {
    interface Raw {
        terminal_id?: string | null;
        terminal_name: string;
        terminal_phone_no: string;
    }
}
