/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const AppPaymentMethod: core.serialization.ObjectSchema<
    serializers.AppPaymentMethod.Raw,
    ShubhiMaheshwariApi.AppPaymentMethod
> = core.serialization.object({
    app: core.serialization.lazyObject(async () => (await import("..")).App),
});

export declare namespace AppPaymentMethod {
    interface Raw {
        app: serializers.App.Raw;
    }
}
