/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const AppProvider: core.serialization.Schema<serializers.AppProvider.Raw, ShubhiMaheshwariApi.AppProvider> =
    core.serialization.enum_(["gpay", "phonepe", "ola", "paytm", "amazon", "airtel", "freecharge", "mobikwik", "jio"]);

export declare namespace AppProvider {
    type Raw = "gpay" | "phonepe" | "ola" | "paytm" | "amazon" | "airtel" | "freecharge" | "mobikwik" | "jio";
}
