/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const AuthenticationError: core.serialization.ObjectSchema<
    serializers.AuthenticationError.Raw,
    ShubhiMaheshwariApi.AuthenticationError
> = core.serialization.object({
    message: core.serialization.string().optional(),
    code: core.serialization.string().optional(),
    type: core.serialization.stringLiteral("authentication_error").optional(),
});

export declare namespace AuthenticationError {
    interface Raw {
        message?: string | null;
        code?: string | null;
        type?: "authentication_error" | null;
    }
}
