/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const AuthorizationInPaymentsEntityAction: core.serialization.Schema<
    serializers.AuthorizationInPaymentsEntityAction.Raw,
    ShubhiMaheshwariApi.AuthorizationInPaymentsEntityAction
> = core.serialization.enum_(["CAPTURE", "VOID"]);

export declare namespace AuthorizationInPaymentsEntityAction {
    type Raw = "CAPTURE" | "VOID";
}
