/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const AuthorizationInPaymentsEntityStatus: core.serialization.Schema<
    serializers.AuthorizationInPaymentsEntityStatus.Raw,
    ShubhiMaheshwariApi.AuthorizationInPaymentsEntityStatus
> = core.serialization.enum_(["SUCCESS", "PENDING"]);

export declare namespace AuthorizationInPaymentsEntityStatus {
    type Raw = "SUCCESS" | "PENDING";
}
