/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const AuthorizationRequestAction: core.serialization.Schema<
    serializers.AuthorizationRequestAction.Raw,
    ShubhiMaheshwariApi.AuthorizationRequestAction
> = core.serialization.enum_(["CAPTURE", "VOID"]);

export declare namespace AuthorizationRequestAction {
    type Raw = "CAPTURE" | "VOID";
}
