/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const AuthorizationInPaymentsEntity: core.serialization.ObjectSchema<
    serializers.AuthorizationInPaymentsEntity.Raw,
    ShubhiMaheshwariApi.AuthorizationInPaymentsEntity
> = core.serialization.object({
    action: core.serialization.lazy(async () => (await import("..")).AuthorizationInPaymentsEntityAction).optional(),
    status: core.serialization.lazy(async () => (await import("..")).AuthorizationInPaymentsEntityStatus).optional(),
    capturedAmount: core.serialization.property("captured_amount", core.serialization.number().optional()),
    startTime: core.serialization.property("start_time", core.serialization.string().optional()),
    endTime: core.serialization.property("end_time", core.serialization.string().optional()),
    approveBy: core.serialization.property("approve_by", core.serialization.string().optional()),
    actionReference: core.serialization.property("action_reference", core.serialization.string().optional()),
    actionTime: core.serialization.property("action_time", core.serialization.string().optional()),
});

export declare namespace AuthorizationInPaymentsEntity {
    interface Raw {
        action?: serializers.AuthorizationInPaymentsEntityAction.Raw | null;
        status?: serializers.AuthorizationInPaymentsEntityStatus.Raw | null;
        captured_amount?: number | null;
        start_time?: string | null;
        end_time?: string | null;
        approve_by?: string | null;
        action_reference?: string | null;
        action_time?: string | null;
    }
}
