/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const CardEmiPaymentMethod: core.serialization.ObjectSchema<
    serializers.CardEmiPaymentMethod.Raw,
    ShubhiMaheshwariApi.CardEmiPaymentMethod
> = core.serialization.object({
    emi: core.serialization.lazyObject(async () => (await import("..")).CardEmi).optional(),
});

export declare namespace CardEmiPaymentMethod {
    interface Raw {
        emi?: serializers.CardEmi.Raw | null;
    }
}
