/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const CardlessEmiPaymentMethod: core.serialization.ObjectSchema<
    serializers.CardlessEmiPaymentMethod.Raw,
    ShubhiMaheshwariApi.CardlessEmiPaymentMethod
> = core.serialization.object({
    cardlessEmi: core.serialization.property(
        "cardless_emi",
        core.serialization.lazyObject(async () => (await import("..")).CardlessEmi)
    ),
});

export declare namespace CardlessEmiPaymentMethod {
    interface Raw {
        cardless_emi: serializers.CardlessEmi.Raw;
    }
}
