/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const CardlessEmi: core.serialization.ObjectSchema<
    serializers.CardlessEmi.Raw,
    ShubhiMaheshwariApi.CardlessEmi
> = core.serialization.object({
    channel: core.serialization.string().optional(),
    provider: core.serialization.lazy(async () => (await import("..")).CardlessEmiProvider).optional(),
    phone: core.serialization.string().optional(),
    emiTenure: core.serialization.property("emi_tenure", core.serialization.number().optional()),
});

export declare namespace CardlessEmi {
    interface Raw {
        channel?: string | null;
        provider?: serializers.CardlessEmiProvider.Raw | null;
        phone?: string | null;
        emi_tenure?: number | null;
    }
}
