/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const CardArray: core.serialization.Schema<serializers.CardArray.Raw, ShubhiMaheshwariApi.CardArray> =
    core.serialization.string();

export declare namespace CardArray {
    type Raw = string;
}
