/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const CardOffer: core.serialization.ObjectSchema<serializers.CardOffer.Raw, ShubhiMaheshwariApi.CardOffer> =
    core.serialization.object({
        type: core.serialization.list(core.serialization.lazy(async () => (await import("..")).CardArray)),
        bankName: core.serialization.property("bank_name", core.serialization.string()),
        schemeName: core.serialization.property(
            "scheme_name",
            core.serialization.list(core.serialization.lazy(async () => (await import("..")).SchemeArray))
        ),
    });

export declare namespace CardOffer {
    interface Raw {
        type: serializers.CardArray.Raw[];
        bank_name: string;
        scheme_name: serializers.SchemeArray.Raw[];
    }
}
