/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const CardEmi: core.serialization.ObjectSchema<serializers.CardEmi.Raw, ShubhiMaheshwariApi.CardEmi> =
    core.serialization.object({
        channel: core.serialization.string().optional(),
        cardNumber: core.serialization.property("card_number", core.serialization.string().optional()),
        cardHolderName: core.serialization.property("card_holder_name", core.serialization.string().optional()),
        cardExpiryMm: core.serialization.property("card_expiry_mm", core.serialization.string().optional()),
        cardExpiryYy: core.serialization.property("card_expiry_yy", core.serialization.string().optional()),
        cardCvv: core.serialization.property("card_cvv", core.serialization.string().optional()),
        cardAlias: core.serialization.property("card_alias", core.serialization.string().optional()),
        cardBankName: core.serialization.property(
            "card_bank_name",
            core.serialization.lazy(async () => (await import("..")).CardEmiCardBankName).optional()
        ),
        emiTenure: core.serialization.property("emi_tenure", core.serialization.number().optional()),
    });

export declare namespace CardEmi {
    interface Raw {
        channel?: string | null;
        card_number?: string | null;
        card_holder_name?: string | null;
        card_expiry_mm?: string | null;
        card_expiry_yy?: string | null;
        card_cvv?: string | null;
        card_alias?: string | null;
        card_bank_name?: serializers.CardEmiCardBankName.Raw | null;
        emi_tenure?: number | null;
    }
}
