/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const CardCardBankName: core.serialization.Schema<
    serializers.CardCardBankName.Raw,
    ShubhiMaheshwariApi.CardCardBankName
> = core.serialization.enum_(["Kotak", "ICICI", "RBL", "BOB", "Standard Chartered"]);

export declare namespace CardCardBankName {
    type Raw = "Kotak" | "ICICI" | "RBL" | "BOB" | "Standard Chartered";
}
