/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const CardPaymentMethod: core.serialization.ObjectSchema<
    serializers.CardPaymentMethod.Raw,
    ShubhiMaheshwariApi.CardPaymentMethod
> = core.serialization.object({
    card: core.serialization.lazyObject(async () => (await import("..")).Card),
});

export declare namespace CardPaymentMethod {
    interface Raw {
        card: serializers.Card.Raw;
    }
}
