/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const CashbackDetails: core.serialization.ObjectSchema<
    serializers.CashbackDetails.Raw,
    ShubhiMaheshwariApi.CashbackDetails
> = core.serialization.object({
    cashbackType: core.serialization.property(
        "cashback_type",
        core.serialization.lazy(async () => (await import("..")).CashbackDetailsCashbackType).optional()
    ),
    cashbackValue: core.serialization.property("cashback_value", core.serialization.string().optional()),
    maxCashbackAmount: core.serialization.property("max_cashback_amount", core.serialization.string()),
});

export declare namespace CashbackDetails {
    interface Raw {
        cashback_type?: serializers.CashbackDetailsCashbackType.Raw | null;
        cashback_value?: string | null;
        max_cashback_amount: string;
    }
}
