/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const CashbackDetailsCashbackType: core.serialization.Schema<
    serializers.CashbackDetailsCashbackType.Raw,
    ShubhiMaheshwariApi.CashbackDetailsCashbackType
> = core.serialization.enum_(["flat", "percentage"]);

export declare namespace CashbackDetailsCashbackType {
    type Raw = "flat" | "percentage";
}
