/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const CreateRefundRequestRefundSpeed: core.serialization.Schema<
    serializers.CreateRefundRequestRefundSpeed.Raw,
    ShubhiMaheshwariApi.CreateRefundRequestRefundSpeed
> = core.serialization.enum_(["STANDARD", "INSTANT"]);

export declare namespace CreateRefundRequestRefundSpeed {
    type Raw = "STANDARD" | "INSTANT";
}
