/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const CustomerDetailsCardlessEmi: core.serialization.ObjectSchema<
    serializers.CustomerDetailsCardlessEmi.Raw,
    ShubhiMaheshwariApi.CustomerDetailsCardlessEmi
> = core.serialization.object({
    customerPhone: core.serialization.property("customer_phone", core.serialization.string()),
});

export declare namespace CustomerDetailsCardlessEmi {
    interface Raw {
        customer_phone: string;
    }
}
