/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const DiscountDetails: core.serialization.ObjectSchema<
    serializers.DiscountDetails.Raw,
    ShubhiMaheshwariApi.DiscountDetails
> = core.serialization.object({
    discountType: core.serialization.property(
        "discount_type",
        core.serialization.lazy(async () => (await import("..")).DiscountDetailsDiscountType)
    ),
    discountValue: core.serialization.property("discount_value", core.serialization.string()),
    maxDiscountAmount: core.serialization.property("max_discount_amount", core.serialization.string()),
});

export declare namespace DiscountDetails {
    interface Raw {
        discount_type: serializers.DiscountDetailsDiscountType.Raw;
        discount_value: string;
        max_discount_amount: string;
    }
}
