/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const DiscountDetailsDiscountType: core.serialization.Schema<
    serializers.DiscountDetailsDiscountType.Raw,
    ShubhiMaheshwariApi.DiscountDetailsDiscountType
> = core.serialization.enum_(["flat", "percentage"]);

export declare namespace DiscountDetailsDiscountType {
    type Raw = "flat" | "percentage";
}
