/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const EligibilityCardlessEmiRequest: core.serialization.ObjectSchema<
    serializers.EligibilityCardlessEmiRequest.Raw,
    ShubhiMaheshwariApi.EligibilityCardlessEmiRequest
> = core.serialization.object({
    queries: core.serialization.lazyObject(async () => (await import("..")).CardlessEmiQueries),
});

export declare namespace EligibilityCardlessEmiRequest {
    interface Raw {
        queries: serializers.CardlessEmiQueries.Raw;
    }
}
