/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const EligiblePaylater: core.serialization.ObjectSchema<
    serializers.EligiblePaylater.Raw,
    ShubhiMaheshwariApi.EligiblePaylater
> = core.serialization.object({
    eligibility: core.serialization.string().optional(),
    entityType: core.serialization.property("entity_type", core.serialization.string().optional()),
    entityValue: core.serialization.property("entity_value", core.serialization.string().optional()),
    entityDetails: core.serialization.property(
        "entity_details",
        core.serialization.lazyObject(async () => (await import("..")).PaylaterEntity).optional()
    ),
});

export declare namespace EligiblePaylater {
    interface Raw {
        eligibility?: string | null;
        entity_type?: string | null;
        entity_value?: string | null;
        entity_details?: serializers.PaylaterEntity.Raw | null;
    }
}
