/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const EmiPlansArray: core.serialization.ObjectSchema<
    serializers.EmiPlansArray.Raw,
    ShubhiMaheshwariApi.EmiPlansArray
> = core.serialization.object({
    tenure: core.serialization.number().optional(),
    interestRate: core.serialization.property("interest_rate", core.serialization.number().optional()),
    currency: core.serialization.string().optional(),
    emi: core.serialization.number().optional(),
    totalInterest: core.serialization.property("total_interest", core.serialization.number().optional()),
    totalAmount: core.serialization.property("total_amount", core.serialization.number().optional()),
});

export declare namespace EmiPlansArray {
    interface Raw {
        tenure?: number | null;
        interest_rate?: number | null;
        currency?: string | null;
        emi?: number | null;
        total_interest?: number | null;
        total_amount?: number | null;
    }
}
