/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const ErrorResponse: core.serialization.ObjectSchema<
    serializers.ErrorResponse.Raw,
    ShubhiMaheshwariApi.ErrorResponse
> = core.serialization.object({
    message: core.serialization.string().optional(),
    code: core.serialization.string().optional(),
    type: core.serialization.lazy(async () => (await import("..")).ErrorResponseType).optional(),
});

export declare namespace ErrorResponse {
    interface Raw {
        message?: string | null;
        code?: string | null;
        type?: serializers.ErrorResponseType.Raw | null;
    }
}
