/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const ErrorResponseType: core.serialization.Schema<
    serializers.ErrorResponseType.Raw,
    ShubhiMaheshwariApi.ErrorResponseType
> = core.serialization.enum_([
    "invalid_request_error",
    "authentication_error",
    "rate_limit_error",
    "validation_error",
    "api_error",
]);

export declare namespace ErrorResponseType {
    type Raw = "invalid_request_error" | "authentication_error" | "rate_limit_error" | "validation_error" | "api_error";
}
