/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const FetchPgReconRequestFilters: core.serialization.ObjectSchema<
    serializers.FetchPgReconRequestFilters.Raw,
    ShubhiMaheshwariApi.FetchPgReconRequestFilters
> = core.serialization.object({
    startDate: core.serialization.property("start_date", core.serialization.string()),
    endDate: core.serialization.property("end_date", core.serialization.string()),
});

export declare namespace FetchPgReconRequestFilters {
    interface Raw {
        start_date: string;
        end_date: string;
    }
}
