/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const FetchSettlementDataItem: core.serialization.ObjectSchema<
    serializers.FetchSettlementDataItem.Raw,
    ShubhiMaheshwariApi.FetchSettlementDataItem
> = core.serialization.object({
    eventType: core.serialization.property("event_type", core.serialization.string().optional()),
    cfSettlementId: core.serialization.property("cf_settlement_id", core.serialization.number().optional()),
    status: core.serialization.string().optional(),
    settlementDate: core.serialization.property("settlement_date", core.serialization.string().optional()),
    paymentAmount: core.serialization.property("payment_amount", core.serialization.number().optional()),
    settlementUtr: core.serialization.property("settlement_utr", core.serialization.string().optional()),
    adjustment: core.serialization.number().optional(),
    serviceTax: core.serialization.property("service_tax", core.serialization.number().optional()),
    serviceCharge: core.serialization.property("service_charge", core.serialization.number().optional()),
    amountSettled: core.serialization.property("amount_settled", core.serialization.number().optional()),
    paymentFrom: core.serialization.property("payment_from", core.serialization.string().optional()),
    paymentTill: core.serialization.property("payment_till", core.serialization.string().optional()),
    reason: core.serialization.string().optional(),
    settlementInitiatedOn: core.serialization.property(
        "settlement_initiated_on",
        core.serialization.string().optional()
    ),
    settlementType: core.serialization.property("settlement_type", core.serialization.string().optional()),
    settlementCharge: core.serialization.property("settlement_charge", core.serialization.number().optional()),
    settlementTax: core.serialization.property("settlement_tax", core.serialization.number().optional()),
    remarks: core.serialization.string().optional(),
});

export declare namespace FetchSettlementDataItem {
    interface Raw {
        event_type?: string | null;
        cf_settlement_id?: number | null;
        status?: string | null;
        settlement_date?: string | null;
        payment_amount?: number | null;
        settlement_utr?: string | null;
        adjustment?: number | null;
        service_tax?: number | null;
        service_charge?: number | null;
        amount_settled?: number | null;
        payment_from?: string | null;
        payment_till?: string | null;
        reason?: string | null;
        settlement_initiated_on?: string | null;
        settlement_type?: string | null;
        settlement_charge?: number | null;
        settlement_tax?: number | null;
        remarks?: string | null;
    }
}
