/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const FetchSettlementReconRequestFilters: core.serialization.ObjectSchema<
    serializers.FetchSettlementReconRequestFilters.Raw,
    ShubhiMaheshwariApi.FetchSettlementReconRequestFilters
> = core.serialization.object({
    cfSettlementIds: core.serialization.property(
        "cf_settlement_ids",
        core.serialization.list(core.serialization.number()).optional()
    ),
    settlementUtrs: core.serialization.property(
        "settlement_utrs",
        core.serialization.list(core.serialization.string()).optional()
    ),
    startDate: core.serialization.property("start_date", core.serialization.string().optional()),
    endDate: core.serialization.property("end_date", core.serialization.string().optional()),
});

export declare namespace FetchSettlementReconRequestFilters {
    interface Raw {
        cf_settlement_ids?: number[] | null;
        settlement_utrs?: string[] | null;
        start_date?: string | null;
        end_date?: string | null;
    }
}
