/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const FetchSettlementReconRequest: core.serialization.ObjectSchema<
    serializers.FetchSettlementReconRequest.Raw,
    ShubhiMaheshwariApi.FetchSettlementReconRequest
> = core.serialization.object({
    pagination: core.serialization.lazyObject(async () => (await import("..")).FetchSettlementReconRequestPagination),
    filters: core.serialization.lazyObject(async () => (await import("..")).FetchSettlementReconRequestFilters),
});

export declare namespace FetchSettlementReconRequest {
    interface Raw {
        pagination: serializers.FetchSettlementReconRequestPagination.Raw;
        filters: serializers.FetchSettlementReconRequestFilters.Raw;
    }
}
