/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const FetchSettlementRecon: core.serialization.ObjectSchema<
    serializers.FetchSettlementRecon.Raw,
    ShubhiMaheshwariApi.FetchSettlementRecon
> = core.serialization.object({
    cursor: core.serialization.string().optional(),
    limit: core.serialization.number().optional(),
    data: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("..")).FetchSettlementReconDataItem))
        .optional(),
});

export declare namespace FetchSettlementRecon {
    interface Raw {
        cursor?: string | null;
        limit?: number | null;
        data?: serializers.FetchSettlementReconDataItem.Raw[] | null;
    }
}
