/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const FetchPgRecon: core.serialization.ObjectSchema<
    serializers.FetchPgRecon.Raw,
    ShubhiMaheshwariApi.FetchPgRecon
> = core.serialization.object({
    cursor: core.serialization.string().optional(),
    limit: core.serialization.number().optional(),
    data: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("..")).FetchPgReconDataItem))
        .optional(),
});

export declare namespace FetchPgRecon {
    interface Raw {
        cursor?: string | null;
        limit?: number | null;
        data?: serializers.FetchPgReconDataItem.Raw[] | null;
    }
}
