/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const GetPaymentsfororderResponse: core.serialization.Schema<
    serializers.GetPaymentsfororderResponse.Raw,
    ShubhiMaheshwariApi.GetPaymentsfororderResponse
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazyObject(async () => (await import("..")).PaymentsEntity),
    core.serialization.lazyObject(async () => (await import("..")).PaymentsEntity),
]);

export declare namespace GetPaymentsfororderResponse {
    type Raw = serializers.PaymentsEntity.Raw | serializers.PaymentsEntity.Raw;
}
