/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const LinkCancelledResponse: core.serialization.ObjectSchema<
    serializers.LinkCancelledResponse.Raw,
    ShubhiMaheshwariApi.LinkCancelledResponse
> = core.serialization.object({
    cfLinkId: core.serialization.property("cf_link_id", core.serialization.number().optional()),
    linkId: core.serialization.property("link_id", core.serialization.string().optional()),
    linkStatus: core.serialization.property("link_status", core.serialization.string().optional()),
    linkCurrency: core.serialization.property("link_currency", core.serialization.string().optional()),
    linkAmount: core.serialization.property("link_amount", core.serialization.number().optional()),
    linkAmountPaid: core.serialization.property("link_amount_paid", core.serialization.number().optional()),
    linkPartialPayments: core.serialization.property("link_partial_payments", core.serialization.boolean().optional()),
    linkMinimumPartialAmount: core.serialization.property(
        "link_minimum_partial_amount",
        core.serialization.number().optional()
    ),
    linkPurpose: core.serialization.property("link_purpose", core.serialization.string().optional()),
    linkCreatedAt: core.serialization.property("link_created_at", core.serialization.string().optional()),
    customerDetails: core.serialization.property(
        "customer_details",
        core.serialization.lazyObject(async () => (await import("..")).LinkCustomerDetailsEntity).optional()
    ),
    linkMeta: core.serialization.property(
        "link_meta",
        core.serialization.lazyObject(async () => (await import("..")).LinkMetaEntity).optional()
    ),
    linkUrl: core.serialization.property("link_url", core.serialization.string().optional()),
    linkExpiryTime: core.serialization.property("link_expiry_time", core.serialization.string().optional()),
    linkNotes: core.serialization.property(
        "link_notes",
        core.serialization.lazy(async () => (await import("..")).LinkNotesEntity).optional()
    ),
    linkAutoReminders: core.serialization.property("link_auto_reminders", core.serialization.boolean().optional()),
    linkNotify: core.serialization.property(
        "link_notify",
        core.serialization.lazyObject(async () => (await import("..")).LinkNotifyEntity).optional()
    ),
});

export declare namespace LinkCancelledResponse {
    interface Raw {
        cf_link_id?: number | null;
        link_id?: string | null;
        link_status?: string | null;
        link_currency?: string | null;
        link_amount?: number | null;
        link_amount_paid?: number | null;
        link_partial_payments?: boolean | null;
        link_minimum_partial_amount?: number | null;
        link_purpose?: string | null;
        link_created_at?: string | null;
        customer_details?: serializers.LinkCustomerDetailsEntity.Raw | null;
        link_meta?: serializers.LinkMetaEntity.Raw | null;
        link_url?: string | null;
        link_expiry_time?: string | null;
        link_notes?: serializers.LinkNotesEntity.Raw | null;
        link_auto_reminders?: boolean | null;
        link_notify?: serializers.LinkNotifyEntity.Raw | null;
    }
}
