/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const LinkOrdersResponse: core.serialization.ObjectSchema<
    serializers.LinkOrdersResponse.Raw,
    ShubhiMaheshwariApi.LinkOrdersResponse
> = core.serialization.object({
    cfOrderId: core.serialization.property("cf_order_id", core.serialization.number().optional()),
    orderId: core.serialization.property("order_id", core.serialization.string().optional()),
    entity: core.serialization.string().optional(),
    orderCurrency: core.serialization.property("order_currency", core.serialization.string().optional()),
    orderAmount: core.serialization.property("order_amount", core.serialization.number().optional()),
    orderStatus: core.serialization.property("order_status", core.serialization.string().optional()),
    orderToken: core.serialization.property("order_token", core.serialization.string().optional()),
    orderExpiryTime: core.serialization.property("order_expiry_time", core.serialization.string().optional()),
    orderNote: core.serialization.property("order_note", core.serialization.string().optional()),
    customerDetails: core.serialization.property(
        "customer_details",
        core.serialization.lazyObject(async () => (await import("..")).LinkCustomerDetailsEntity).optional()
    ),
    payments: core.serialization.lazyObject(async () => (await import("..")).PaymentUrlObject).optional(),
    settlements: core.serialization.lazyObject(async () => (await import("..")).SettlementUrlObject).optional(),
    refunds: core.serialization.lazyObject(async () => (await import("..")).RefundUrlObject).optional(),
});

export declare namespace LinkOrdersResponse {
    interface Raw {
        cf_order_id?: number | null;
        order_id?: string | null;
        entity?: string | null;
        order_currency?: string | null;
        order_amount?: number | null;
        order_status?: string | null;
        order_token?: string | null;
        order_expiry_time?: string | null;
        order_note?: string | null;
        customer_details?: serializers.LinkCustomerDetailsEntity.Raw | null;
        payments?: serializers.PaymentUrlObject.Raw | null;
        settlements?: serializers.SettlementUrlObject.Raw | null;
        refunds?: serializers.RefundUrlObject.Raw | null;
    }
}
