/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const LinkNotifyEntity: core.serialization.ObjectSchema<
    serializers.LinkNotifyEntity.Raw,
    ShubhiMaheshwariApi.LinkNotifyEntity
> = core.serialization.object({
    sendSms: core.serialization.property("send_sms", core.serialization.boolean().optional()),
    sendEmail: core.serialization.property("send_email", core.serialization.boolean().optional()),
});

export declare namespace LinkNotifyEntity {
    interface Raw {
        send_sms?: boolean | null;
        send_email?: boolean | null;
    }
}
