/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const LinkCancelledError: core.serialization.ObjectSchema<
    serializers.LinkCancelledError.Raw,
    ShubhiMaheshwariApi.LinkCancelledError
> = core.serialization.object({
    message: core.serialization.string().optional(),
    code: core.serialization.string().optional(),
    type: core.serialization.string().optional(),
});

export declare namespace LinkCancelledError {
    interface Raw {
        message?: string | null;
        code?: string | null;
        type?: string | null;
    }
}
