/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const LinkNotesEntity: core.serialization.Schema<
    serializers.LinkNotesEntity.Raw,
    ShubhiMaheshwariApi.LinkNotesEntity
> = core.serialization.record(core.serialization.string(), core.serialization.string());

export declare namespace LinkNotesEntity {
    type Raw = Record<string, string>;
}
