/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const LinkCustomerDetailsEntity: core.serialization.ObjectSchema<
    serializers.LinkCustomerDetailsEntity.Raw,
    ShubhiMaheshwariApi.LinkCustomerDetailsEntity
> = core.serialization.object({
    customerPhone: core.serialization.property("customer_phone", core.serialization.string()),
    customerEmail: core.serialization.property("customer_email", core.serialization.string().optional()),
    customerName: core.serialization.property("customer_name", core.serialization.string().optional()),
});

export declare namespace LinkCustomerDetailsEntity {
    interface Raw {
        customer_phone: string;
        customer_email?: string | null;
        customer_name?: string | null;
    }
}
