/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const LinkMetaEntity: core.serialization.ObjectSchema<
    serializers.LinkMetaEntity.Raw,
    ShubhiMaheshwariApi.LinkMetaEntity
> = core.serialization.object({
    notifyUrl: core.serialization.property("notify_url", core.serialization.string().optional()),
    upiIntent: core.serialization.property("upi_intent", core.serialization.boolean().optional()),
    returnUrl: core.serialization.property("return_url", core.serialization.string().optional()),
    paymentMethods: core.serialization.property("payment_methods", core.serialization.string().optional()),
});

export declare namespace LinkMetaEntity {
    interface Raw {
        notify_url?: string | null;
        upi_intent?: boolean | null;
        return_url?: string | null;
        payment_methods?: string | null;
    }
}
