/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const NbOffer: core.serialization.ObjectSchema<serializers.NbOffer.Raw, ShubhiMaheshwariApi.NbOffer> =
    core.serialization.object({
        bankName: core.serialization.property("bank_name", core.serialization.string()),
    });

export declare namespace NbOffer {
    interface Raw {
        bank_name: string;
    }
}
