/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const Netbanking: core.serialization.ObjectSchema<serializers.Netbanking.Raw, ShubhiMaheshwariApi.Netbanking> =
    core.serialization.object({
        channel: core.serialization.string(),
        netbankingBankCode: core.serialization.property("netbanking_bank_code", core.serialization.number()),
    });

export declare namespace Netbanking {
    interface Raw {
        channel: string;
        netbanking_bank_code: number;
    }
}
