/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const OfferDetailsOfferType: core.serialization.Schema<
    serializers.OfferDetailsOfferType.Raw,
    ShubhiMaheshwariApi.OfferDetailsOfferType
> = core.serialization.enum_(["DISCOUNT", "CASHBACK", "DISCOUNT_AND_CASHBACK", "NO_COST_EMI"]);

export declare namespace OfferDetailsOfferType {
    type Raw = "DISCOUNT" | "CASHBACK" | "DISCOUNT_AND_CASHBACK" | "NO_COST_EMI";
}
