/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const OfferEntity: core.serialization.ObjectSchema<
    serializers.OfferEntity.Raw,
    ShubhiMaheshwariApi.OfferEntity
> = core.serialization.object({
    offerId: core.serialization.property("offer_id", core.serialization.number().optional()),
    offerStatus: core.serialization.property("offer_status", core.serialization.string().optional()),
    offerMeta: core.serialization.property(
        "offer_meta",
        core.serialization.lazyObject(async () => (await import("..")).OfferMeta).optional()
    ),
    offerTnc: core.serialization.property(
        "offer_tnc",
        core.serialization.lazyObject(async () => (await import("..")).OfferTnc).optional()
    ),
    offerDetails: core.serialization.property(
        "offer_details",
        core.serialization.lazyObject(async () => (await import("..")).OfferDetails).optional()
    ),
    offerValidations: core.serialization.property(
        "offer_validations",
        core.serialization.lazyObject(async () => (await import("..")).OfferValidations).optional()
    ),
});

export declare namespace OfferEntity {
    interface Raw {
        offer_id?: number | null;
        offer_status?: string | null;
        offer_meta?: serializers.OfferMeta.Raw | null;
        offer_tnc?: serializers.OfferTnc.Raw | null;
        offer_details?: serializers.OfferDetails.Raw | null;
        offer_validations?: serializers.OfferValidations.Raw | null;
    }
}
