/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const OfferMeta: core.serialization.ObjectSchema<serializers.OfferMeta.Raw, ShubhiMaheshwariApi.OfferMeta> =
    core.serialization.object({
        offerTitle: core.serialization.property("offer_title", core.serialization.string()),
        offerDescription: core.serialization.property("offer_description", core.serialization.string()),
        offerCode: core.serialization.property("offer_code", core.serialization.string()),
        offerStartTime: core.serialization.property("offer_start_time", core.serialization.string()),
        offerEndTime: core.serialization.property("offer_end_time", core.serialization.string()),
    });

export declare namespace OfferMeta {
    interface Raw {
        offer_title: string;
        offer_description: string;
        offer_code: string;
        offer_start_time: string;
        offer_end_time: string;
    }
}
