/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const OfferTnc: core.serialization.ObjectSchema<serializers.OfferTnc.Raw, ShubhiMaheshwariApi.OfferTnc> =
    core.serialization.object({
        offerTncType: core.serialization.property(
            "offer_tnc_type",
            core.serialization.lazy(async () => (await import("..")).OfferTncOfferTncType)
        ),
        offerTncValue: core.serialization.property("offer_tnc_value", core.serialization.string()),
    });

export declare namespace OfferTnc {
    interface Raw {
        offer_tnc_type: serializers.OfferTncOfferTncType.Raw;
        offer_tnc_value: string;
    }
}
