/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const OfferWallet: core.serialization.ObjectSchema<
    serializers.OfferWallet.Raw,
    ShubhiMaheshwariApi.OfferWallet
> = core.serialization.object({
    app: core.serialization.lazyObject(async () => (await import("..")).WalletOffer).optional(),
});

export declare namespace OfferWallet {
    interface Raw {
        app?: serializers.WalletOffer.Raw | null;
    }
}
