/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const OfferFilters: core.serialization.ObjectSchema<
    serializers.OfferFilters.Raw,
    ShubhiMaheshwariApi.OfferFilters
> = core.serialization.object({
    offerType: core.serialization.property(
        "offer_type",
        core.serialization.list(core.serialization.lazy(async () => (await import("..")).OfferType)).optional()
    ),
});

export declare namespace OfferFilters {
    interface Raw {
        offer_type?: serializers.OfferType.Raw[] | null;
    }
}
