/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const OfferQueries: core.serialization.ObjectSchema<
    serializers.OfferQueries.Raw,
    ShubhiMaheshwariApi.OfferQueries
> = core.serialization.object({
    orderId: core.serialization.property("order_id", core.serialization.string().optional()),
    amount: core.serialization.number().optional(),
});

export declare namespace OfferQueries {
    interface Raw {
        order_id?: string | null;
        amount?: number | null;
    }
}
