/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const OfferUpi: core.serialization.ObjectSchema<serializers.OfferUpi.Raw, ShubhiMaheshwariApi.OfferUpi> =
    core.serialization.object({
        upi: core.serialization.lazy(async () => (await import("..")).UpiOffer),
    });

export declare namespace OfferUpi {
    interface Raw {
        upi: serializers.UpiOffer.Raw;
    }
}
