/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const OfferTncOfferTncType: core.serialization.Schema<
    serializers.OfferTncOfferTncType.Raw,
    ShubhiMaheshwariApi.OfferTncOfferTncType
> = core.serialization.enum_(["link", "post"]);

export declare namespace OfferTncOfferTncType {
    type Raw = "link" | "post";
}
