/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const OfferValidationsPaymentMethod: core.serialization.Schema<
    serializers.OfferValidationsPaymentMethod.Raw,
    ShubhiMaheshwariApi.OfferValidationsPaymentMethod
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazyObject(async () => (await import("..")).OfferAll),
    core.serialization.lazyObject(async () => (await import("..")).OfferCard),
    core.serialization.lazyObject(async () => (await import("..")).OfferNb),
    core.serialization.lazyObject(async () => (await import("..")).OfferWallet),
    core.serialization.lazyObject(async () => (await import("..")).OfferUpi),
    core.serialization.lazyObject(async () => (await import("..")).OfferPaylater),
    core.serialization.lazyObject(async () => (await import("..")).OfferEmi),
]);

export declare namespace OfferValidationsPaymentMethod {
    type Raw =
        | serializers.OfferAll.Raw
        | serializers.OfferCard.Raw
        | serializers.OfferNb.Raw
        | serializers.OfferWallet.Raw
        | serializers.OfferUpi.Raw
        | serializers.OfferPaylater.Raw
        | serializers.OfferEmi.Raw;
}
