/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const OfferDetails: core.serialization.ObjectSchema<
    serializers.OfferDetails.Raw,
    ShubhiMaheshwariApi.OfferDetails
> = core.serialization.object({
    offerType: core.serialization.property(
        "offer_type",
        core.serialization.lazy(async () => (await import("..")).OfferDetailsOfferType)
    ),
    discountDetails: core.serialization.property(
        "discount_details",
        core.serialization.lazyObject(async () => (await import("..")).DiscountDetails).optional()
    ),
    cashbackDetails: core.serialization.property(
        "cashback_details",
        core.serialization.lazyObject(async () => (await import("..")).CashbackDetails).optional()
    ),
});

export declare namespace OfferDetails {
    interface Raw {
        offer_type: serializers.OfferDetailsOfferType.Raw;
        discount_details?: serializers.DiscountDetails.Raw | null;
        cashback_details?: serializers.CashbackDetails.Raw | null;
    }
}
