/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const OfferNb: core.serialization.ObjectSchema<serializers.OfferNb.Raw, ShubhiMaheshwariApi.OfferNb> =
    core.serialization.object({
        netbanking: core.serialization.lazyObject(async () => (await import("..")).NbOffer).optional(),
    });

export declare namespace OfferNb {
    interface Raw {
        netbanking?: serializers.NbOffer.Raw | null;
    }
}
