/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const OfferEmi: core.serialization.ObjectSchema<serializers.OfferEmi.Raw, ShubhiMaheshwariApi.OfferEmi> =
    core.serialization.object({
        emi: core.serialization.lazyObject(async () => (await import("..")).EmiOffer),
    });

export declare namespace OfferEmi {
    interface Raw {
        emi: serializers.EmiOffer.Raw;
    }
}
