/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const OfferCard: core.serialization.ObjectSchema<serializers.OfferCard.Raw, ShubhiMaheshwariApi.OfferCard> =
    core.serialization.object({
        card: core.serialization.lazyObject(async () => (await import("..")).CardOffer),
    });

export declare namespace OfferCard {
    interface Raw {
        card: serializers.CardOffer.Raw;
    }
}
