/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const OfferPaylater: core.serialization.ObjectSchema<
    serializers.OfferPaylater.Raw,
    ShubhiMaheshwariApi.OfferPaylater
> = core.serialization.object({
    paylater: core.serialization.lazyObject(async () => (await import("..")).PaylaterOffer),
});

export declare namespace OfferPaylater {
    interface Raw {
        paylater: serializers.PaylaterOffer.Raw;
    }
}
