/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const OrderMeta: core.serialization.ObjectSchema<serializers.OrderMeta.Raw, ShubhiMaheshwariApi.OrderMeta> =
    core.serialization.object({
        returnUrl: core.serialization.property("return_url", core.serialization.string().optional()),
        notifyUrl: core.serialization.property("notify_url", core.serialization.string().optional()),
        paymentMethods: core.serialization.property("payment_methods", core.serialization.string().optional()),
    });

export declare namespace OrderMeta {
    interface Raw {
        return_url?: string | null;
        notify_url?: string | null;
        payment_methods?: string | null;
    }
}
