/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const OrderPayResponseChannel: core.serialization.Schema<
    serializers.OrderPayResponseChannel.Raw,
    ShubhiMaheshwariApi.OrderPayResponseChannel
> = core.serialization.enum_(["link", "collect", "qrcode"]);

export declare namespace OrderPayResponseChannel {
    type Raw = "link" | "collect" | "qrcode";
}
