/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const OrderPayResponsePaymentMethod: core.serialization.Schema<
    serializers.OrderPayResponsePaymentMethod.Raw,
    ShubhiMaheshwariApi.OrderPayResponsePaymentMethod
> = core.serialization.enum_(["netbanking", "card", "upi", "app", "cardless_emi", "paylater"]);

export declare namespace OrderPayResponsePaymentMethod {
    type Raw = "netbanking" | "card" | "upi" | "app" | "cardless_emi" | "paylater";
}
