/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const OrdersEntity: core.serialization.ObjectSchema<
    serializers.OrdersEntity.Raw,
    ShubhiMaheshwariApi.OrdersEntity
> = core.serialization.object({
    cfOrderId: core.serialization.property("cf_order_id", core.serialization.number().optional()),
    orderId: core.serialization.property("order_id", core.serialization.string().optional()),
    entity: core.serialization.string().optional(),
    orderCurrency: core.serialization.property("order_currency", core.serialization.string().optional()),
    orderAmount: core.serialization.property("order_amount", core.serialization.number().optional()),
    orderStatus: core.serialization.property("order_status", core.serialization.string().optional()),
    paymentSessionId: core.serialization.property("payment_session_id", core.serialization.string().optional()),
    orderExpiryTime: core.serialization.property("order_expiry_time", core.serialization.string().optional()),
    orderNote: core.serialization.property("order_note", core.serialization.string().optional()),
    customerDetails: core.serialization.property(
        "customer_details",
        core.serialization.lazyObject(async () => (await import("..")).CustomerDetails).optional()
    ),
    orderMeta: core.serialization.property(
        "order_meta",
        core.serialization.lazyObject(async () => (await import("..")).OrderMeta).optional()
    ),
    payments: core.serialization.lazyObject(async () => (await import("..")).PaymentUrlObject).optional(),
    settlements: core.serialization.lazyObject(async () => (await import("..")).SettlementUrlObject).optional(),
    refunds: core.serialization.lazyObject(async () => (await import("..")).RefundUrlObject).optional(),
});

export declare namespace OrdersEntity {
    interface Raw {
        cf_order_id?: number | null;
        order_id?: string | null;
        entity?: string | null;
        order_currency?: string | null;
        order_amount?: number | null;
        order_status?: string | null;
        payment_session_id?: string | null;
        order_expiry_time?: string | null;
        order_note?: string | null;
        customer_details?: serializers.CustomerDetails.Raw | null;
        order_meta?: serializers.OrderMeta.Raw | null;
        payments?: serializers.PaymentUrlObject.Raw | null;
        settlements?: serializers.SettlementUrlObject.Raw | null;
        refunds?: serializers.RefundUrlObject.Raw | null;
    }
}
