/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const OrderPayResponseAction: core.serialization.Schema<
    serializers.OrderPayResponseAction.Raw,
    ShubhiMaheshwariApi.OrderPayResponseAction
> = core.serialization.enum_(["link", "custom", "form"]);

export declare namespace OrderPayResponseAction {
    type Raw = "link" | "custom" | "form";
}
