/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const OtpResponseEntity: core.serialization.ObjectSchema<
    serializers.OtpResponseEntity.Raw,
    ShubhiMaheshwariApi.OtpResponseEntity
> = core.serialization.object({
    cfPaymentId: core.serialization.property("cf_payment_id", core.serialization.number().optional()),
    action: core.serialization.lazy(async () => (await import("..")).OtpResponseEntityAction).optional(),
    authenticateStatus: core.serialization.property(
        "authenticate_status",
        core.serialization.lazy(async () => (await import("..")).OtpResponseEntityAuthenticateStatus).optional()
    ),
    paymentMessage: core.serialization.property("payment_message", core.serialization.string().optional()),
});

export declare namespace OtpResponseEntity {
    interface Raw {
        cf_payment_id?: number | null;
        action?: serializers.OtpResponseEntityAction.Raw | null;
        authenticate_status?: serializers.OtpResponseEntityAuthenticateStatus.Raw | null;
        payment_message?: string | null;
    }
}
