/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const OtpResponseEntityAction: core.serialization.Schema<
    serializers.OtpResponseEntityAction.Raw,
    ShubhiMaheshwariApi.OtpResponseEntityAction
> = core.serialization.enum_(["SUBMIT_OTP", "RESEND_OTP"]);

export declare namespace OtpResponseEntityAction {
    type Raw = "SUBMIT_OTP" | "RESEND_OTP";
}
