/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const PaylaterOffer: core.serialization.ObjectSchema<
    serializers.PaylaterOffer.Raw,
    ShubhiMaheshwariApi.PaylaterOffer
> = core.serialization.object({
    provider: core.serialization.string().optional(),
});

export declare namespace PaylaterOffer {
    interface Raw {
        provider?: string | null;
    }
}
