/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const PaylaterPaymentMethod: core.serialization.ObjectSchema<
    serializers.PaylaterPaymentMethod.Raw,
    ShubhiMaheshwariApi.PaylaterPaymentMethod
> = core.serialization.object({
    paylater: core.serialization.lazyObject(async () => (await import("..")).Paylater),
});

export declare namespace PaylaterPaymentMethod {
    interface Raw {
        paylater: serializers.Paylater.Raw;
    }
}
