/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const Paylater: core.serialization.ObjectSchema<serializers.Paylater.Raw, ShubhiMaheshwariApi.Paylater> =
    core.serialization.object({
        channel: core.serialization.string().optional(),
        provider: core.serialization.lazy(async () => (await import("..")).PaylaterProvider).optional(),
        phone: core.serialization.string().optional(),
    });

export declare namespace Paylater {
    interface Raw {
        channel?: string | null;
        provider?: serializers.PaylaterProvider.Raw | null;
        phone?: string | null;
    }
}
