/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const PaylaterProvider: core.serialization.Schema<
    serializers.PaylaterProvider.Raw,
    ShubhiMaheshwariApi.PaylaterProvider
> = core.serialization.enum_([
    "kotak",
    "flexipay",
    "zestmoney",
    "lazypay",
    "olapostpaid",
    "simpl",
    "freechargepaylater",
]);

export declare namespace PaylaterProvider {
    type Raw = "kotak" | "flexipay" | "zestmoney" | "lazypay" | "olapostpaid" | "simpl" | "freechargepaylater";
}
