/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const PaymentsEntityPaymentStatus: core.serialization.Schema<
    serializers.PaymentsEntityPaymentStatus.Raw,
    ShubhiMaheshwariApi.PaymentsEntityPaymentStatus
> = core.serialization.enum_(["SUCCESS", "NOT_ATTEMPTED", "FAILED", "USER_DROPPED", "VOID", "CANCELLED", "PENDING"]);

export declare namespace PaymentsEntityPaymentStatus {
    type Raw = "SUCCESS" | "NOT_ATTEMPTED" | "FAILED" | "USER_DROPPED" | "VOID" | "CANCELLED" | "PENDING";
}
