/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const PaymentSuccessWebhook: core.serialization.ObjectSchema<
    serializers.PaymentSuccessWebhook.Raw,
    ShubhiMaheshwariApi.PaymentSuccessWebhook
> = core.serialization.object({
    data: core.serialization.lazyObject(async () => (await import("..")).WHdata).optional(),
    eventTime: core.serialization.property("event_time", core.serialization.string().optional()),
    type: core.serialization.string().optional(),
});

export declare namespace PaymentSuccessWebhook {
    interface Raw {
        data?: serializers.WHdata.Raw | null;
        event_time?: string | null;
        type?: string | null;
    }
}
