/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const PaymentMethodUpiInPaymentsEntity: core.serialization.ObjectSchema<
    serializers.PaymentMethodUpiInPaymentsEntity.Raw,
    ShubhiMaheshwariApi.PaymentMethodUpiInPaymentsEntity
> = core.serialization.object({
    channel: core.serialization.string(),
    upiId: core.serialization.property("upi_id", core.serialization.string().optional()),
});

export declare namespace PaymentMethodUpiInPaymentsEntity {
    interface Raw {
        channel: string;
        upi_id?: string | null;
    }
}
