/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const PaymentMethodNetBankingInPaymentsEntity: core.serialization.ObjectSchema<
    serializers.PaymentMethodNetBankingInPaymentsEntity.Raw,
    ShubhiMaheshwariApi.PaymentMethodNetBankingInPaymentsEntity
> = core.serialization.object({
    channel: core.serialization.string(),
    netbankingBankCode: core.serialization.property("netbanking_bank_code", core.serialization.string()),
    netbankingBankName: core.serialization.property("netbanking_bank_name", core.serialization.string()),
});

export declare namespace PaymentMethodNetBankingInPaymentsEntity {
    interface Raw {
        channel: string;
        netbanking_bank_code: string;
        netbanking_bank_name: string;
    }
}
