/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const RateLimitError: core.serialization.ObjectSchema<
    serializers.RateLimitError.Raw,
    ShubhiMaheshwariApi.RateLimitError
> = core.serialization.object({
    message: core.serialization.string().optional(),
    code: core.serialization.string().optional(),
    type: core.serialization.stringLiteral("rate_limit_error").optional(),
});

export declare namespace RateLimitError {
    interface Raw {
        message?: string | null;
        code?: string | null;
        type?: "rate_limit_error" | null;
    }
}
