/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const RefundSpeed: core.serialization.ObjectSchema<
    serializers.RefundSpeed.Raw,
    ShubhiMaheshwariApi.RefundSpeed
> = core.serialization.object({
    requested: core.serialization.string().optional(),
    accepted: core.serialization.string().optional(),
    processed: core.serialization.string().optional(),
    message: core.serialization.string().optional(),
});

export declare namespace RefundSpeed {
    interface Raw {
        requested?: string | null;
        accepted?: string | null;
        processed?: string | null;
        message?: string | null;
    }
}
