/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const RefundsEntityRefundMode: core.serialization.Schema<
    serializers.RefundsEntityRefundMode.Raw,
    ShubhiMaheshwariApi.RefundsEntityRefundMode
> = core.serialization.enum_(["STANDARD", "INSTANT"]);

export declare namespace RefundsEntityRefundMode {
    type Raw = "STANDARD" | "INSTANT";
}
