/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const RefundUrlObject: core.serialization.ObjectSchema<
    serializers.RefundUrlObject.Raw,
    ShubhiMaheshwariApi.RefundUrlObject
> = core.serialization.object({
    url: core.serialization.string().optional(),
});

export declare namespace RefundUrlObject {
    interface Raw {
        url?: string | null;
    }
}
