/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const SavedInstrumentMeta: core.serialization.ObjectSchema<
    serializers.SavedInstrumentMeta.Raw,
    ShubhiMaheshwariApi.SavedInstrumentMeta
> = core.serialization.object({
    cardNetwork: core.serialization.property("card_network", core.serialization.string().optional()),
    cardBankName: core.serialization.property("card_bank_name", core.serialization.string().optional()),
    cardCountry: core.serialization.property("card_country", core.serialization.string().optional()),
    cardType: core.serialization.property("card_type", core.serialization.string().optional()),
    cardTokenDetails: core.serialization.property(
        "card_token_details",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional()
    ),
});

export declare namespace SavedInstrumentMeta {
    interface Raw {
        card_network?: string | null;
        card_bank_name?: string | null;
        card_country?: string | null;
        card_type?: string | null;
        card_token_details?: Record<string, unknown> | null;
    }
}
