/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const SchemeArray: core.serialization.Schema<serializers.SchemeArray.Raw, ShubhiMaheshwariApi.SchemeArray> =
    core.serialization.string();

export declare namespace SchemeArray {
    type Raw = string;
}
