/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const SettlementsEntity: core.serialization.ObjectSchema<
    serializers.SettlementsEntity.Raw,
    ShubhiMaheshwariApi.SettlementsEntity
> = core.serialization.object({
    cfPaymentId: core.serialization.property("cf_payment_id", core.serialization.string().optional()),
    cfSettlementId: core.serialization.property("cf_settlement_id", core.serialization.string().optional()),
    settlementCurrency: core.serialization.property("settlement_currency", core.serialization.string().optional()),
    orderId: core.serialization.property("order_id", core.serialization.string().optional()),
    entity: core.serialization.string().optional(),
    orderAmount: core.serialization.property("order_amount", core.serialization.number().optional()),
    paymentTime: core.serialization.property("payment_time", core.serialization.string().optional()),
    serviceCharge: core.serialization.property("service_charge", core.serialization.number().optional()),
    serviceTax: core.serialization.property("service_tax", core.serialization.number().optional()),
    settlementAmount: core.serialization.property("settlement_amount", core.serialization.number().optional()),
    settlementId: core.serialization.property("settlement_id", core.serialization.number().optional()),
    transferId: core.serialization.property("transfer_id", core.serialization.number().optional()),
    transferTime: core.serialization.property("transfer_time", core.serialization.string().optional()),
    transferUtr: core.serialization.property("transfer_utr", core.serialization.string().optional()),
});

export declare namespace SettlementsEntity {
    interface Raw {
        cf_payment_id?: string | null;
        cf_settlement_id?: string | null;
        settlement_currency?: string | null;
        order_id?: string | null;
        entity?: string | null;
        order_amount?: number | null;
        payment_time?: string | null;
        service_charge?: number | null;
        service_tax?: number | null;
        settlement_amount?: number | null;
        settlement_id?: number | null;
        transfer_id?: number | null;
        transfer_time?: string | null;
        transfer_utr?: string | null;
    }
}
