/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const SettlementUrlObject: core.serialization.ObjectSchema<
    serializers.SettlementUrlObject.Raw,
    ShubhiMaheshwariApi.SettlementUrlObject
> = core.serialization.object({
    url: core.serialization.string().optional(),
});

export declare namespace SettlementUrlObject {
    interface Raw {
        url?: string | null;
    }
}
