/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const TenuresArray: core.serialization.Schema<serializers.TenuresArray.Raw, ShubhiMaheshwariApi.TenuresArray> =
    core.serialization.number();

export declare namespace TenuresArray {
    type Raw = number;
}
