/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const TerminalDetails: core.serialization.ObjectSchema<
    serializers.TerminalDetails.Raw,
    ShubhiMaheshwariApi.TerminalDetails
> = core.serialization.object({
    terminalPhoneNo: core.serialization.property("terminal_phone_no", core.serialization.string()),
    terminalId: core.serialization.property("terminal_id", core.serialization.string()),
    terminalType: core.serialization.property("terminal_type", core.serialization.string()),
});

export declare namespace TerminalDetails {
    interface Raw {
        terminal_phone_no: string;
        terminal_id: string;
        terminal_type: string;
    }
}
