/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const TerminalResponse: core.serialization.ObjectSchema<
    serializers.TerminalResponse.Raw,
    ShubhiMaheshwariApi.TerminalResponse
> = core.serialization.object({
    addedOn: core.serialization.property("added_on", core.serialization.string().optional()),
    cfTerminalId: core.serialization.property("cf_terminal_id", core.serialization.string().optional()),
    lastUpdatedOn: core.serialization.property("last_updated_on", core.serialization.string().optional()),
    terminalArea: core.serialization.property("terminal_area", core.serialization.string().optional()),
    teminalId: core.serialization.property("teminal_id", core.serialization.string().optional()),
    terminalName: core.serialization.property("terminal_name", core.serialization.string().optional()),
    terminalNote: core.serialization.property("terminal_note", core.serialization.string().optional()),
    terminalPhoneNo: core.serialization.property("terminal_phone_no", core.serialization.string().optional()),
    terminalStatus: core.serialization.property("terminal_status", core.serialization.string().optional()),
});

export declare namespace TerminalResponse {
    interface Raw {
        added_on?: string | null;
        cf_terminal_id?: string | null;
        last_updated_on?: string | null;
        terminal_area?: string | null;
        teminal_id?: string | null;
        terminal_name?: string | null;
        terminal_note?: string | null;
        terminal_phone_no?: string | null;
        terminal_status?: string | null;
    }
}
