/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const Upi: core.serialization.ObjectSchema<serializers.Upi.Raw, ShubhiMaheshwariApi.Upi> =
    core.serialization.object({
        channel: core.serialization.lazy(async () => (await import("..")).UpiChannel),
        upiId: core.serialization.property("upi_id", core.serialization.string().optional()),
        upiExpiryMinutes: core.serialization.property("upi_expiry_minutes", core.serialization.number().optional()),
        authorizeOnly: core.serialization.property("authorize_only", core.serialization.boolean().optional()),
        authorization: core.serialization.lazyObject(async () => (await import("..")).UpiAuthorizeDetails).optional(),
    });

export declare namespace Upi {
    interface Raw {
        channel: serializers.UpiChannel.Raw;
        upi_id?: string | null;
        upi_expiry_minutes?: number | null;
        authorize_only?: boolean | null;
        authorization?: serializers.UpiAuthorizeDetails.Raw | null;
    }
}
