/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const UpiAuthorizeDetails: core.serialization.ObjectSchema<
    serializers.UpiAuthorizeDetails.Raw,
    ShubhiMaheshwariApi.UpiAuthorizeDetails
> = core.serialization.object({
    approveBy: core.serialization.property("approve_by", core.serialization.string().optional()),
    startTime: core.serialization.property("start_time", core.serialization.string().optional()),
    endTime: core.serialization.property("end_time", core.serialization.string().optional()),
});

export declare namespace UpiAuthorizeDetails {
    interface Raw {
        approve_by?: string | null;
        start_time?: string | null;
        end_time?: string | null;
    }
}
