/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const UpiChannel: core.serialization.Schema<serializers.UpiChannel.Raw, ShubhiMaheshwariApi.UpiChannel> =
    core.serialization.enum_(["link", "collect", "qrcode"]);

export declare namespace UpiChannel {
    type Raw = "link" | "collect" | "qrcode";
}
