/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const UpiPaymentMethod: core.serialization.ObjectSchema<
    serializers.UpiPaymentMethod.Raw,
    ShubhiMaheshwariApi.UpiPaymentMethod
> = core.serialization.object({
    upi: core.serialization.lazyObject(async () => (await import("..")).Upi),
});

export declare namespace UpiPaymentMethod {
    interface Raw {
        upi: serializers.Upi.Raw;
    }
}
