/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const VendorSplit: core.serialization.ObjectSchema<
    serializers.VendorSplit.Raw,
    ShubhiMaheshwariApi.VendorSplit
> = core.serialization.object({
    vendorId: core.serialization.property("vendor_id", core.serialization.string().optional()),
    amount: core.serialization.number().optional(),
    percentage: core.serialization.number().optional(),
});

export declare namespace VendorSplit {
    interface Raw {
        vendor_id?: string | null;
        amount?: number | null;
        percentage?: number | null;
    }
}
