/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const WalletOffer: core.serialization.ObjectSchema<
    serializers.WalletOffer.Raw,
    ShubhiMaheshwariApi.WalletOffer
> = core.serialization.object({
    provider: core.serialization.string().optional(),
});

export declare namespace WalletOffer {
    interface Raw {
        provider?: string | null;
    }
}
