/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const WHcard: core.serialization.ObjectSchema<serializers.WHcard.Raw, ShubhiMaheshwariApi.WHcard> =
    core.serialization.object({
        channel: core.serialization.string().optional(),
        cardNumber: core.serialization.property("card_number", core.serialization.string().optional()),
        cardNetwork: core.serialization.property("card_network", core.serialization.string().optional()),
        cardType: core.serialization.property("card_type", core.serialization.string().optional()),
        cardCounty: core.serialization.property("card_county", core.serialization.string().optional()),
        cardBankName: core.serialization.property("card_bank_name", core.serialization.string().optional()),
    });

export declare namespace WHcard {
    interface Raw {
        channel?: string | null;
        card_number?: string | null;
        card_network?: string | null;
        card_type?: string | null;
        card_county?: string | null;
        card_bank_name?: string | null;
    }
}
