/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const WHcustomerDetails: core.serialization.ObjectSchema<
    serializers.WHcustomerDetails.Raw,
    ShubhiMaheshwariApi.WHcustomerDetails
> = core.serialization.object({
    customerName: core.serialization.property("customer_name", core.serialization.string().optional()),
    customerId: core.serialization.property("customer_id", core.serialization.string().optional()),
    customerEmail: core.serialization.property("customer_email", core.serialization.string().optional()),
    customerPhone: core.serialization.property("customer_phone", core.serialization.string().optional()),
});

export declare namespace WHcustomerDetails {
    interface Raw {
        customer_name?: string | null;
        customer_id?: string | null;
        customer_email?: string | null;
        customer_phone?: string | null;
    }
}
