/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const WHdata: core.serialization.ObjectSchema<serializers.WHdata.Raw, ShubhiMaheshwariApi.WHdata> =
    core.serialization.object({
        order: core.serialization.lazyObject(async () => (await import("..")).WHorder).optional(),
        payment: core.serialization.lazyObject(async () => (await import("..")).WHpayment).optional(),
        customerDetails: core.serialization.property(
            "customer_details",
            core.serialization.lazyObject(async () => (await import("..")).WHcustomerDetails).optional()
        ),
    });

export declare namespace WHdata {
    interface Raw {
        order?: serializers.WHorder.Raw | null;
        payment?: serializers.WHpayment.Raw | null;
        customer_details?: serializers.WHcustomerDetails.Raw | null;
    }
}
