/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const WHorder: core.serialization.ObjectSchema<serializers.WHorder.Raw, ShubhiMaheshwariApi.WHorder> =
    core.serialization.object({
        orderId: core.serialization.property("order_id", core.serialization.string().optional()),
        orderAmount: core.serialization.property("order_amount", core.serialization.number().optional()),
        orderCurrency: core.serialization.property("order_currency", core.serialization.string().optional()),
        orderTags: core.serialization.property("order_tags", core.serialization.string().optional()),
    });

export declare namespace WHorder {
    interface Raw {
        order_id?: string | null;
        order_amount?: number | null;
        order_currency?: string | null;
        order_tags?: string | null;
    }
}
