/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as ShubhiMaheshwariApi from "../../api";
import * as core from "../../core";

export const WHpayment: core.serialization.ObjectSchema<serializers.WHpayment.Raw, ShubhiMaheshwariApi.WHpayment> =
    core.serialization.object({
        cfPaymentId: core.serialization.property("cf_payment_id", core.serialization.string().optional()),
        paymentStatus: core.serialization.property("payment_status", core.serialization.string().optional()),
        paymentAmount: core.serialization.property("payment_amount", core.serialization.number().optional()),
        paymentCurrency: core.serialization.property("payment_currency", core.serialization.string().optional()),
        paymentMessage: core.serialization.property("payment_message", core.serialization.string().optional()),
        paymentTime: core.serialization.property("payment_time", core.serialization.string().optional()),
        bankReference: core.serialization.property("bank_reference", core.serialization.string().optional()),
        authId: core.serialization.property("auth_id", core.serialization.string().optional()),
        paymentMethod: core.serialization.property(
            "payment_method",
            core.serialization.lazyObject(async () => (await import("..")).WHpaymentMethod).optional()
        ),
        paymentGroup: core.serialization.property("payment_group", core.serialization.string().optional()),
    });

export declare namespace WHpayment {
    interface Raw {
        cf_payment_id?: string | null;
        payment_status?: string | null;
        payment_amount?: number | null;
        payment_currency?: string | null;
        payment_message?: string | null;
        payment_time?: string | null;
        bank_reference?: string | null;
        auth_id?: string | null;
        payment_method?: serializers.WHpaymentMethod.Raw | null;
        payment_group?: string | null;
    }
}
