/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "../../../..";

export interface CreateLinkRequest {
    /** Unique Identifier (provided by merchant) for the Link. Alphanumeric and only - and _ allowed (50 character limit). Use this for other link-related APIs. <span style="white-space: nowrap">`<= 50 characters`</span> */
    linkId: string;
    /** Amount to be collected using this link. Provide upto two decimals for paise. */
    linkAmount: number;
    /** Currency for the payment link. Default is INR. Contact care@cashfree.com to enable new currencies. <span style="white-space: nowrap">`<= 3 characters`</span> */
    linkCurrency: string;
    /** A brief description for which payment must be collected. This is shown to the customer. <span style="white-space: nowrap">`<= 500 characters`</span> */
    linkPurpose: string;
    customerDetails: ShubhiMaheshwariApi.LinkCustomerDetailsEntity;
    /** If "true", customer can make partial payments for the link. */
    linkPartialPayments?: boolean;
    /** Minimum amount in first installment that needs to be paid by the customer if partial payments are enabled. This should be less than the link_amount. */
    linkMinimumPartialAmount?: number;
    /** Time after which the link expires. Customers will not be able to make the payment beyond the time specified here. You can provide them in a valid ISO 8601 time format. Default is 30 days. */
    linkExpiryTime?: string;
    linkNotify?: ShubhiMaheshwariApi.LinkNotifyEntity;
    /** If "true", reminders will be sent to customers for collecting payments. */
    linkAutoReminders?: boolean;
    linkNotes?: ShubhiMaheshwariApi.LinkNotesEntity;
    linkMeta?: ShubhiMaheshwariApi.LinkMetaEntity;
}
