/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ShubhiMaheshwariApi from "../../../..";

export interface EligibilityOffersRequest {
    queries: ShubhiMaheshwariApi.OfferQueries;
    filters?: ShubhiMaheshwariApi.OfferFilters;
}
