/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as ShubhiMaheshwariApi from "../../../../../api";
import * as core from "../../../../../core";

export const CreateRefundRequest: core.serialization.Schema<
    serializers.CreateRefundRequest.Raw,
    ShubhiMaheshwariApi.CreateRefundRequest
> = core.serialization.object({
    refundAmount: core.serialization.property("refund_amount", core.serialization.number()),
    refundId: core.serialization.property("refund_id", core.serialization.string()),
    refundNote: core.serialization.property("refund_note", core.serialization.string().optional()),
    refundSpeed: core.serialization.property(
        "refund_speed",
        core.serialization.lazy(async () => (await import("../../../..")).CreateRefundRequestRefundSpeed).optional()
    ),
    refundSplits: core.serialization.property(
        "refund_splits",
        core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../../..")).VendorSplit))
            .optional()
    ),
});

export declare namespace CreateRefundRequest {
    interface Raw {
        refund_amount: number;
        refund_id: string;
        refund_note?: string | null;
        refund_speed?: serializers.CreateRefundRequestRefundSpeed.Raw | null;
        refund_splits?: serializers.VendorSplit.Raw[] | null;
    }
}
