/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as ShubhiMaheshwariApi from "../../../../../api";
import * as core from "../../../../../core";

export const OtpRequest: core.serialization.Schema<serializers.OtpRequest.Raw, ShubhiMaheshwariApi.OtpRequest> =
    core.serialization.object({
        otp: core.serialization.string(),
        action: core.serialization.lazy(async () => (await import("../../../..")).OtpRequestAction),
    });

export declare namespace OtpRequest {
    interface Raw {
        otp: string;
        action: serializers.OtpRequestAction.Raw;
    }
}
