/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as ShubhiMaheshwariApi from "../../../../api";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.refunds.getallrefundsfororder.Response.Raw,
    ShubhiMaheshwariApi.RefundsEntity[]
> = core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).RefundsEntity));

export declare namespace Response {
    type Raw = serializers.RefundsEntity.Raw[];
}
